\documentclass{tufte-book} %[openany] option unselected


\usepackage{../include/RBook}
\usepackage{pdfpages}
%\usepackage[shownotes]{authNote}
\usepackage[hidenotes]{../include/authNote}
\usepackage{../include/language}
\usepackage{hyperref}
\usepackage{fancyhdr} % DTK added for header.
\usepackage[T1]{fontenc}
\usepackage{selinput}


% Larger font sizes (from size12.clo)
\makeatletter% allows us to use macros with @ in their names
\renewcommand\normalsize{%
   \@setfontsize\normalsize\@xiipt{14.5}%
   \abovedisplayskip 12\p@ \@plus3\p@ \@minus7\p@
   \abovedisplayshortskip \z@ \@plus3\p@
   \belowdisplayshortskip 6.5\p@ \@plus3.5\p@ \@minus3\p@
   \belowdisplayskip \abovedisplayskip
   \let\@listi\@listI}
\renewcommand\small{%
   \@setfontsize\small\@xipt{13.6}%
   \abovedisplayskip 11\p@ \@plus3\p@ \@minus6\p@
   \abovedisplayshortskip \z@ \@plus3\p@
   \belowdisplayshortskip 6.5\p@ \@plus3.5\p@ \@minus3\p@
   \def\@listi{\leftmargin\leftmargini
               \topsep 9\p@ \@plus3\p@ \@minus5\p@
               \parsep 4.5\p@ \@plus2\p@ \@minus\p@
               \itemsep \parsep}%
   \belowdisplayskip \abovedisplayskip
}
\renewcommand\footnotesize{%
   \@setfontsize\footnotesize\@xpt\@xiipt
   \abovedisplayskip 10\p@ \@plus2\p@ \@minus5\p@
   \abovedisplayshortskip \z@ \@plus3\p@
   \belowdisplayshortskip 6\p@ \@plus3\p@ \@minus3\p@
   \def\@listi{\leftmargin\leftmargini
               \topsep 6\p@ \@plus2\p@ \@minus2\p@
               \parsep 3\p@ \@plus2\p@ \@minus\p@
               \itemsep \parsep}%
   \belowdisplayskip \abovedisplayskip
}
\renewcommand\scriptsize{\@setfontsize\scriptsize\@viiipt{9.5}}
\renewcommand\tiny{\@setfontsize\tiny\@vipt\@viipt}
\renewcommand\large{\@setfontsize\large\@xivpt{18}}
\renewcommand\Large{\@setfontsize\Large\@xviipt{22}}
\renewcommand\LARGE{\@setfontsize\LARGE\@xxpt{25}}
\renewcommand\huge{\@setfontsize\huge\@xxvpt{30}}
\let\Huge=\huge
\setlength\leftmargini   {1.5em}
\setlength\leftmarginii  {1.5em}
\setlength\leftmarginiii {1.5em}
\setlength\leftmarginiv  {1.5em}
\setlength\leftmarginv   {1.5em}
\setlength\leftmarginvi  {1.5em}
\setlength\labelsep      {.5pc}
\setlength\labelwidth    {\leftmargini}
\addtolength\labelwidth{-\labelsep}
\setlength{\parindent}{1.5em}%
\renewcommand{\@tufte@reset@par}{%
  \setlength{\RaggedRightParindent}{1.5em}%
  \setlength{\JustifyingParindent}{1.5em}%
  \setlength{\parindent}{1.5em}%
  \setlength{\parskip}{0pt}%
}
\@tufte@reset@par
\renewcommand{\@tufte@margin@par}{%
  \setlength{\RaggedRightParindent}{1.0em}%
  \setlength{\JustifyingParindent}{1.0em}%
  \setlength{\parindent}{1.0em}%
  \setlength{\parskip}{0pt}%
}
\makeatother% restores meaning of @

% For the printed version.  Commented out for Web version
\renewcommand{\variable}[1]{{\color{black}\texttt{#1}}}
\renewcommand{\dataframe}[1]{{\color{black}\texttt{#1}}}
\renewcommand{\function}[1]{{\color{blue}\texttt{\StrSubstitute{#1}{()}{}()}}}
\renewcommand{\option}[1]{{\color{black}\texttt{#1}}}
\renewcommand{\pkg}[1]{{\color{black}\texttt{#1}}}
\renewcommand{\code}[1]{{\color{black}\texttt{#1}}}



\title{Una Guía de Estudiantes para R}
\author[Horton, Kaplan, Pruim]{ Nicholas J. Horton, Daniel Kaplan, and Randall Pruim} 
\date{Noviembre 2015}

\begin{document}
\SweaveOpts{concordance=TRUE}
\def\cplabel{^X} 

\def\tilde{\texttt{\~}}
% stupid hack to get rid of unwanted space before next line when there is not
% a blank line following an R chunk.


<<include=F, results=hide, message=FALSE, warnings=FALSE, echo=FALSE>>=
#setCacheDir("cache")
require(MASS)   # commented out by NJH 9/27/2015
require(grDevices) 
require(datasets) 
require(stats) 
require(lattice)
require(grid) 
require(fastR)	# commented out by NH on 7/12/2012
require(mosaic) 
require(mosaicData) 
trellis.par.set(theme=col.mosaic(bw=FALSE))
trellis.par.set(fontsize=list(text=9))
options(format.R.blank=FALSE) 
options(width=70)
options(continue=" ")
require(knitr)
opts_chunk$set(  tidy=FALSE,
			     size='small',
                 dev="pdf",
                 fig.path="figures/fig-",  
                 fig.width=4, fig.height=2.4,
                 fig.align="center",
                 fig.show="hold",
 		 prompt=TRUE,
                 comment=NA)
 # For printing in black and white
opts_chunk$set( fig.path="figure/Core-fig-" ) 
set.seed(123)
@

<<include=FALSE, echo=FALSE>>=
includeChapter <- FALSE # don't show chapters not yet being paginated.
showEdited <- FALSE  # displaying chapters already paginated for printing
#knit_hooks$set(document = function(x) { 
#			   sub('\\usepackage[]{color}', '\\usepackage[]{xcolor}', 
#			   x, fixed = TRUE) 
#}) 

knit_hooks$set(document = function(x) { 
  gsub('(\\\\end\\{knitrout\\})\n', '\\1', x) 
}) 
@

\maketitle
%\includepdf[trim=0 0 3.5cm 0]{Cover/frontice}

\newpage
\vspace*{2in}

\parbox{4in}{\noindent La traducción al español de este libro fue realizada por Francisco Javier Jara Ávila. En caso de encontrar errores en la misma, siéntase libre de escribir a fjaraavila@gmail.com}

\bigskip

\parbox{4in}{\noindent Copyright (c) 2015 by Nicholas J. Horton, Randall Pruim, \& Daniel Kaplan.}
\medskip

\parbox{4in}{\noindent Edition 1.2, November 2015}

\bigskip

\parbox{4in}{\noindent This material is copyrighted by the authors under a Creative Commons Attribution 3.0 Unported License. You are free to \emph{Share} (to copy, distribute and transmit the work) and to \emph{Remix} (to adapt the work) if you attribute our work. More detailed information about the licensing is available at this web page:
\url{http://www.mosaic-web.org/go/teachingRlicense.html}.
}


\vspace*{2.in}

\parbox{4in}{\noindent {\bf Cover Photo}: Maya Hanna.}


\hspace*{1.3cm}\tableofcontents


\chapter*{Acerca de estas notas}
<<include=FALSE, message=FALSE, echo=FALSE>>=
opts_chunk$set( fig.path="figures/FrontMatter-" ) 
@

Aquí presentamos un abordaje a la enseñanza introductoria e intermedia en cursos de estadística, la cual está acoplada importantemente con la computación general, y con \R\ y \RStudio\ RStudio en particular. Estas actividades y ejemplos tienen la intención de resaltar el abordaje moderno de la enseñanza estadística que se concentra en el modelaje, la inferencia basada en el re-muestreo y las técnicas de gráficos multivariados. Una meta secundaria es facilitar los cálculos con datos mediante el uso de pequeños estudios de simulaciones y el flujo de trabajo de análisis estadístico apropiado. Esto sigue la filosofía descrita por Nolan y Temple Lang1\cite{nola:temp:2010}. La importancia de la computación moderna \marginnote{$\ $} en la educación estadística consiste en que esta es un componente principal de los  lineamientos de currículo recientemente adoptados de la Asociación Americana de Estadística\cite{ASAcurriculum2014}.

En este libro (y en sus volúmenes acompañantes), introduciremos múltiples actividades, algunas apropiadas para un curso introductorio, otras maleables para niveles superiores, que demuestran conceptos claves de estadística y modelaje, mientras también ofrecen ayuda al material de base de cursos más tradicionales.

\subsection*{Un trabajo en progreso}

\Caution{A pesar de nuestros mejores esfuerzos, VA a encontrar fallas en este documento y en nuestro código. Por favor háganos saber cuándo las encuentre para poder resolverlas..}%

Estos materiales fueron construidos para un taller llamado
\emph{Teaching Statistics Using R} (Enseñando estadística con R) anterior a la  United States Conference on Teaching Statistics y fue corregido para USCOTS 2011, USCOTS 2013, eCOTS 2014, ICOTS 9, and USCOTS 2015.

Organizamos todos estos talleres para ayudar a los instructores a integrar \R\ R (así como otras tecnologías relacionadas) en los cursos de estadística de todos los niveles.

Recibimos una gran retroalimentación y bastantes buenas ideas por parte de participantes y por parte de aquellos con los que compartimos este material en 
los talleres.

Considere las notas como un trabajo en progreso.
%\SuggestionBox{En ocasiones vamos a marcar 
%partes en las cuales nos gustaría retroalimentación con este buzón de sugerencias
%Pero no lo haremos en todas las secciones que queremos retroalimentación porque si no,
% no tendríamos espacio para nada más.}%
Apreciaremos cualquier retroalimentación que esté dispuesto a compartirnos, conforme continuamos el trabajo en estos materiales y el acompañante del material, el paquete \pkg{mosaic}.  
Envíenos un email a \url{pis@mosaic-web.org} con cualquier comentario, sugerencia, corrección, etc

Versiones actualizadas del paquete serán publicadas en  \url{http://mosaic-web.org}.

\subsection*{Dos audiencias}

Inicialmente desarrollamos estos materiales para instructores y profesores de estadística a nivel universitario. Otra audiencia para la cual desarrollamos el material son los estudiantes a quién estos instructores o profesores enseñan. Algunas de las secciones, algunos de los ejemplos y  algunos ejercicios están pensados para una u otra de estas audiencias, con una mayor claridad en el énfasis que se le da a la audiencia. Esto significa que:
\begin{enumerate}
\item Algunos materiales son utilizados esencialmente para los estudiantes.
\item Algunos materiales apuntan a equipar al instructor a explotar sus propias capacidades en \R\ and \RStudio\ para desarrollar su propio material de enseñanza.
\end{enumerate}

Aunque la distinción puede volverse confusa, y lo que funciona "así" en una condición puede no funcionar "así" en otras, intentaremos indicarle cuales partes se ajustan  a cual audiencia conforme vayamos por ella.

\subsection*{R, RStudio y los paquetes de R}

\R\ puede ser obtenido  \url{http://cran.r-project.org/}.  
La descarga e instalación es abierta y sencilla para máquinas con MAC, PC o linux

\RStudio\ es una interfaz de desarrollo integrada (IDE por sus siglas en inglés) que facilita el uso de \R\ tanto para usuarios sin experiencia como usuarios expertos.  Lo hemos adaptado como nuestra interfaz standard de enseñanza puesto que simplifica drásticamente el uso de \R\ para instructores y estudiantes.%

\Pointer[-3cm]{Algunas cosas sólo pueden ser ejecutadas en RStudio, como la función \function{manipulate} y la herramienta de RStudio para la investigación reproducible.}%

\RStudio\ está disponible en \url{http://www.rstudio.org/}.

\RStudio\ . RStudio puede instalarse como aplicación de escritorio o como una aplicación en un servidor accesible a los usuarios vía Internet.\FoodForThought[-.5cm]{La versión en un servidor web de RStudio funciona bien con estudiantes que están iniciando. Lo único que se  necesita es un navegador web, evadiendo todos los potenciales problemas con particularidades de la computadora personal de cada estudiante.}

Además de \R\ y \RStudio\, haremos uso de algunos paquetes que necesitan ser instalados y cargados separadamente. El paquete \pkg{mosaic} (y sus dependencias) serán utilizados en todo momento. Otros paquetes aparecerán esporádicamente.
\subsection*{Notas marginales}
Las notas marginales aparecerán por aquí y por allá
%\DiggingDeeper{Some marginal notes will look like this one and provide
%some additional information that you may find of interest.}%
\marginnote{¿Tiene alguna sugerencia para una nota marginal? Compártala con nosotros.}%
En ocasiones estas son comentarios extra que deseábamos hacer, pero no queríamos interrumpir el flujo de la lectura y mencionarlos en el texto principal. Otras proveen consejos para la enseñanza o precauciones acerca de trampas, caídas y 'jugadas'.
%\Caution{Sin embargo, las alertas están ajustadas diferentes, asegúrese de prestarles atención.}%

\subsection*{Lo que es nuestro, es suyo, hasta cierto punto}
Este material se encuentra en copyright por los autores, bajo 'Creative Commons Attribution 3.0 Unported License'.
Está libre para \emph{compartirlo} (copiarlo, distribuirlo y transferir el trabajo) y \emph{mezclarlo} 
(adaptar el trabajo) si nos atribuye el  trabajo realizado.
Para información más detallada sobre esto, está disponible en el siguiente sitio web:
\url{http://www.mosaic-web.org/go/teachingRlicense.html}.


\DiggingDeeper{Si usted conoce LaTeX tan bien como R, entonces el paquete knitr ofrece una buena solución para mezclar ambos. Nosotros utilizamos este sistema para producir este libro. También lo utilizamos para nuestra propia investigación y para introducir a estudiantes de nivel superior a métodos de análisis reproducible. Para principiantes, introducimos knitr con RMarkdown, el cual produce archivos en formato PDF, HTML o Word utilizando sintaxis sencilla}

\subsection*{Creación del documento}

El documento original fue creado el 12 de Agosto de 2016, utilizando: knitr, versión 1.13.2 mosaic, versión 0.14.9000 *R version 3.3.0 (2016-05-03)

Inevitablemente, cada una de estas va ser actualizada en ciertas ocasiones. Si usted encuentra cosas que se ven diferente en su computadora, asegúrese que su versión de \R{} y sus paquetes estén actualizados y revise versiones más nuevas de este documento

Honores y agradecimientos a Joseph Cappelleri por sus comentarios útiles en los primeros borradores de este material

chapter*{Proyecto MOSAIC}
Este libro es producto del Proyecto MOSAIC, una comunidad de educadores trabajando para desarrollar nuevas formas de introducir las matemáticas, la estadística, la computación y el modelaje de datos a estudiantes universitarios.

\bigskip

La meta del proyecto MOSAIC es ayudar a compartir ideas y recursos para mejorar la enseñanza, y desarrollar una estructura curricular y valorativa para dar apoyo a la diseminación y evaluación de estos esfuerzos. Nuestra meta es proveer un amplio acercamiento a los estudios cuantitativos que brindan una mejor herramienta al trabajo en la ciencia y tecnología. El proyecto resalta e integra diversos aspectos del trabajo cuantitativo que los estudiantes de ciencia, tecnología e ingeniería necesitarán en sus vidas profesionales, pero que actualmente es usual que sean enseñados de forma aislada, si es que acaso se enseñan. En particular, nos concentramos en:

\vspace{.1in}

En particular nos enfocamos en:
\begin{description}
	\item[Modelaje] La habilidad de crear, manipular e investigar representaciones matemáticas útiles e informativas de situaciones del mundo real.

	\item[Estadística] El análisis de variabilidad que se esboza de nuestra habilidad de cuantificar la incertidumbre y generar inferencias lógicas de observación y experimentación.

    \item[Computación] 
	La capacidad de pensar algorítmicamente, de manejar datos en gran escala, visualizar e interactuar con modelos, y automatizar tareas para la eficiencia, precisión y reproducibilidad.

    \item[Cálculo] 
	El punto de entrada tradicional para estudiantes universitarios y un tema que todavía hoy tiene la capacidad de dotar de nociones importantes a los estudiantes
	\end{description}

Tomando el apoyo de la Fundación Nacional de Ciencia de Estados Unidos (NSF DUE-0920350), 
Proyecto MOSAIC apoya algunas iniciativas para ayudar a lograr estas metas, 
incluyendo:
\begin{description}
\item
[Desarrollo de facultades y oportunidad de entrenamiento] 
así como en USCOTS 2011, USCOTS 2013, eCOTS 2014, e ICOTS9 en los talleres
\emph{'Teaching Statistics Using \R\ y \RStudio}, en 2010 nuestro Proyecto MOSAIC inició talleres en el Instituto de Matemática y sus aplicaciones, y nuestro taller  \emph{Modeling: Early and Often in Undergraduate Calculus}
AMS PREP fueron ofrecidos en 2012,  2013, and 2015.

\item
[M-casts,] 
una serie de seminarios web programados regularmente, dados vía Internet,  
en el que se creó foro para que los instructores puedan compartir sus observaciones e innovaciones 
y desarrollar colaboraciones para refinar y desarrollar las mismas.
Las grabaciones de los M-casts están
disponibles en el sitio web del Proyecto MOSAIC, \url{http://mosaic-web.org}.
\item[La construcción de un programa y materiales] 
para cursos que enseña MOSAIC con tópicos integrados de la mejor manera. Estos
Estos cursos y materiales podrían ser completamente nuevas construcciones,
o podrían ser modificaciones de 
recursos existentes que se aproximen 
a las conexiones entre los tópicos de MOSAIC.
\end{description}

Más detalles pueden ser encontrados en \url{http://www.mosaic-web.org}.
Le damos la bienvenida e incitamos su participación en todas estas iniciativas.

\chapter*{Estadística computacional}

Hay al menos dos formas en las cuales se puede introducir un software
estadístico en un curso de estadística.  En el primer abordaje, el curso debe ser enseñado esencialmente como 
se hacía anterior a la utilización de los software estadísticos, pero utilizando la computadora para hacer más rápidos algunos cálculos y generar gráficos de alta calidad displays.  PProbablemente el tamaño de los conjuntos de datos también deba ser incrementado. Nos referiremos a este enfoque como
\term{computación estadística} 
puesto que la computadora funciona primariamente como una herramienta de cálculo para reemplazar los cálculos en lápiz y papel, además del dibujo manual de los gráficos.

En el segundo abordaje, cambios más importantes en el curso resultan de la introducción de la computadora. Algunos temas nuevos son cubiertos, algunos temas anteriores son omitidos. Algunos temas anteriores son tratados en formas muy diferentes, y quizás en diferentes etapas en el curso.  A este abordaje nos referiremos como \term{estadística computacional} bporque la disponibilidad de la computación está moldeando como la estadística es construida y enseñada. La estadística computacional es un componente clave de la  \term{ciencia de los datos}, definida como la habilidad de usar datos para responder preguntas y comunicar resultados.

\FoodForThought{Los estudiantes necesitan ver los aspectos de la computación y la ciencia de los datos de manera pronta y cotidiana para desarrollar habilidades profundas. Establecer bases en cursos introductorios ayuda a que inicien de mejor manera.}%

En la práctica, la mayoría de los cursos van a incorporar elementos de ambas, la estadística computacional y la computación estadística, pero las proporciones relativas pueden diferir drásticamente de curso a curso. En qué parte del espectro se encuentra el curso va depender de muchos factores, incluyendo las metas del curso, la disponibilidad de tecnología para el uso de los estudiantes, la perspectiva del libro utilizado y el nivel de 'comfort' que sienta el instructor con la estadística y la computación.

Entre los varios paquetes de software estadístico disponible, \R\ está incrementando su popularidad. La reciente adición de \RStudio\ ha hecho R más poderoso y accesible. Como \R\ y \RStudio\ son gratis, ambos se han vuelto ampliamente utilizados en la investigación y la industria. Entrenar en \R\ y \RStudio\ es normalmente visto como una habilidad adicional importante que un curso de estadística puede desarrollar. Por esto, un alto número de instructores están utilizando \R\ para su propio trabajo estadístico; por lo que es natural que inicien a integrarlo en la enseñanza también. Al mismo tiempo, el desarrollo de \R\ y \RStudio\ (una interfaz opcional e integrada al desarrollo de un entorno para \R) están haciendo cada vez más fácil iniciar la utilización de \R.

\FoodForThought{La información sobre el paquete \pkg{mosaic}, incluyendo ejemplos de características y material suplementario (así como este libro) puede encontrarla en \url{https://cran.r-project.org/web/packages/mosaic}.}
Desarrollamos el paquete de \R\ \pkg{mosaic} (disponible en CRAN), para hacer ciertos aspectos de la computación estadística y la estadística computacional más simple para inexpertos, sin limitar su habilidad a utilizar características del lenguaje.  El paquete \pkg{mosaic} incluye un acercamiento al modelaje, que utiliza la misma sintaxis general para calcular estadísticas descriptivas, crear gráficos y ajustar modelos lineales.

\chapter{Introducción}

\vspace*{-.5cm}

En este libro de referencia, resumidamente repasamos comandos y funciones necesarias para analizar datos desde cursos introductorios hasta secundarios de estadística  . Esto con la intención de complementar los libros \emph{Empiece a enseñar con R} and \emph{Start Modeling with R} books.

La mayoría de nuestros ejemplos van a utilizar datos del estudio HELP (Health Evaluation and Linkage to Primary Care): un ensayo clínico aleatorizado buscando conectar pacientes en riesgo con el cuidado primario de salud. Más información del conjunto de datos se puede encontrar en el capítulo 14.


Como la selección y el orden de los temas pueden variar de libro a libro y de instructor a instructor, hemos decidido organizar este material por tipo de datos que están siendo analizados. Esto debe hacerse dirigido a encontrar lo que se está buscando. Algunas habilidades en manejo de datos pueden ser necesitadas por los estudiantes\cite{hort:2015}. Una introducción básica a expresiones clave se da en el capítulo 13.
\ref{sec:manipulatingData}.

\myindex{vignettes}%
Este proyecto se aventaja de las iniciativas tomadas por el Proyecto MOSAIC (\url{http://www.mosaic-web.org}), un esfuerzo financiado por la NSF para mejorar la enseñanza de la estadística, el cálculo, la ciencia y la computación en el currículo de los programas de grado. En particular, utilizamos el paquete \pkg{mosaic}, el cual fue escrito para simplificar el uso de \R\ para los cursos introductorios de estadística, y el paquete \pkg{mosaicData} que incluye algunos archivos de datos. Un pequeño resumen de los comandos de \R\ necesarios para la enseñanza de estadística introductoria puede ser encontrado en el siguiente sitio:
\url{https://cran.r-project.org/web/packages/mosaic}.

Otros recursos relacionados del Proyecto MOSAIC pueden ser de ayuda, incluyendo un conjunto de ejemplos anotados de la quinta edción de Moore, McCabe y Craig \emph{Introduction to the Practice of Statistics}\cite{moor:mcca:2007} (ver \url{http://www.amherst.edu/~nhorton/ips6e}), la segunda y tercera edición de  \emph{Statistical Sleuth}\cite{Sleuth2} (ver \url{http://www.amherst.edu/~nhorton/sleuth}), and \emph{Statistics: Unlocking the Power of Data} por Lock et al (see \url{https://github.com/rpruim/Lock5withR}).

\myindex{installing packages}%
\Rindex{install.packages()}%
Para usar el paquete dentro de R, este debe ser instalado (una vez), y cargado (cada sesión). El paquete \pkg{mosaic} puede ser instalado utilizando el siguiente comando: 
<<install_mosaic,eval=FALSE>>=
install.packages("mosaic")  # Observe las comillas
@
\FoodForThought[-1.5cm]{\Rstudio\ dispone forma más simplificada de instalación de paquetes (en el panel de arriba a la derecha).} El {\tt \#} es un comentario en R, y todo el texto después de ese símbolo es ignorado a la hora de ejecutar el código.

\myindex{loading packages}%
\Rindex{require()}%
O Una vez que el paquete es instalado (una única vez), puede ser cargado ejecutando el siguiente comando:
<<load_mosaic,eval=FALSE>>=
require(mosaic)
@

\FoodForThought[-3cm]{El sistema \pkg{knitr}/\LaTeX\ permite combinar \R\ y \LaTeX\ en el mismo documento.  La recompensa por aprender este sistema más complicado es un control más fino sobre el formato del documento de salida. Pero RMarkdown es más sencillo de aprender y adecuar incluso en el trabajo a nivel profesional.}%


\myindex{reproducible analysis}%
\myindex{markdown}%
\myindex{knitr}%
\marginnote[.4cm]{Usar Markdown o \pkg{knitr}/\LaTeX\ requiere que el paquete \pkg{markdown} esté instalado.}%
TEl sistema de RMarkdown aporta una adición en el lenguaje y produce documentos en PDF, Word o HTML. Esto permite a los estudiantes tomar sus análisis utilizando un flujo de trabajo que facilita la "reproducibilidad" y evita copiar y pegar errores.

Usualmente introducimos a los estudiantes a RMarkdown de forma muy pronta, pidiéndoles que lo utilicen para tareas y reportes\cite{baum:2014}.


\chapter{Empezando con RStudio}
\label{chap:RStudio}

\RStudio\ es un entorno integrado de desarrollo (IDE por sus siglas en inglés) para \R\ que proporciona una alternativa de interface de \R, que tiene algunas ventajas sobre la interfaz predeterminada de \R: 
\FoodForThought{Una serie de videos para iniciar con R está disponible en: \url{http://www.amherst.edu/~nhorton/rstudio}.}
\begin{itemize}
	\item \RStudio\ es ejecutable en máquinas Mac, PC o Linux y brinda  
	  una interfaz simplificada que
	  \emph{se ve y se siente idéntico en todas ellas.}
La interface predeterminada de \R\ es un poco diferente en las distintas plataformas.  Esto
		es un distractor para los estudiantes y agrega una responsabilidad extra de conocimiento 
		al instructor
	\item
		\RStudio\ puede ejecutarse desde un navegador web.

		Además de la versión para escritorio, RStudio puede ser utilizado y configurado 
		como una aplicación en un servidor al que se tiene acceso vía internet  

		La interfaz web es prácticamente idéntica a la versión de escritorio.%
		\Caution{La versión de escritorio y la versión del servidor de \RStudio\ son tan similares
		tendrá que prestar mucha atención y asegúrarse
		de que este trabajando en la que tenía intención de trabajar.}
		Como con otros servicios web, el usuario debe hacer un inicio de sesión para acceder a su cuenta.
		Si los estudiantes cierran sesión y abren sesión después, incluso en una máquina diferente,
	la sesión es restaurada y pueden continuar sus análisis
		justo donde los dejaron.
		Con un poco de ajustes avanzados, los instructores pueden salvar el registro de su utilización de \R\ 
		classroom \R\ use and students en clase y pueden cargar estos archivos de registro en su propio 
		entorno.%
		\Note{Usar \RStudio\ en un navegador es como Facebook para estadística
		Cada vez que el usuario vuelve, la sesión previa es restaurada
		y puede continuar el trabajo donde lo dejó. Los usuarios pueden iniciar sesión desde cualquier dispositivo  
		con acceso a internet.}%
	\item
		\RStudio\ brinda apoyo para la investigación reproducible..

		\RStudio\ RStudio facilita incluir texto, análisis estadístico (código de \R\ 
		 y salidas de \R), y gráficos, todo en un mismo documento.
		 El sistema de RMarkdown proporciona una adición en el lenguaje y 
		 produce documentos en HTML. El sistema \pkg{knitr}/\LaTeX\ 
		 permite a los usuarios combinar  \R\ y \LaTeX\ en el mismo documento.  La
		 rrecompensa por aprender este sistema más complicado es un control más fino 
		 sobre el formato del documento de salida. Dependiendo del nivel del curso, 
		los estudiantes pueden usar esto para tareas y proyectos.  
		 \authNote{NH (via rjp): Add some pointers to more information?}
		 \marginnote{Para usar Markdown o \pkg{knitr}/\LaTeX\ se requiere que 
		 el paquete  \pkg{knitr} esté instalado en su sistema.  }
		 

	 \item
		 \RStudio\ pofrece una opción integrada para editar y ejecutar
		 código de \R\, y documentos.

	 \item
		 \RStudio\ provee una interfaz funcional de gráficos para el usuario.

		 \RStudio\ RStudio no es un GUI para \R\, pero este sí brinda una GUI 
		 que simplifica cosas como instalar y actualizar los paquetes; monitorear, guardar y cargar 
		 entornos; importar y exportar datos; navegar y exportar gráficos; y navegar por archivos y documentación.


	 \item
		 \RStudio\ permite el acceso al paquete \pkg{manipulate} 

		 El paquete \pkg{manipulate} brinda una forma de crear aplicaciones gráficas interactivas
		 de forma rápida y sencilla.

\end{itemize}

Realmente se puede usar  \R\ sin usar \RStudio, sin embargo, \RStudio\ hace una cantidad considerable de cosas
más sencillas, recomendamos vigorosamente la utilización de  \RStudio.  Además puesto que \RStudio\
RStudio está en desarrollo activo, tenemos la expectativa de más características útiles en el futuro.


Primordialmente utilizamos una versión online de \Rstudio\ .  \RStudio\ es una interfaz innovadora y poderosa para \R\, que se ejecuta en un navegador web o en su computadora.
Ejecutarlo en el navegador tiene la ventaja de que no se necesita instalar 
o configurar nada.  . Solo inicia sesión y está listo.  Entonces, , RStudio va "recordar" lo que estuvo haciendo cada vez que inicie sesión (incluso en una máquina diferente), 
usted puede elegir iniciar justo donde usted lo dejó.
Esto es "\R\ en la nube" y funciona un poco como GoogleDocs o Facebook para \R.

\R\ se puede obtener también de \url{http://cran.r-project.org/}.  
La descarga y la instalación son dirigidas a máquinas Mac, PC o Linux
\RStudio\ RStudio está disponible en \url{http://www.rstudio.org/}.

\section{Conectándose al servidor de RStudio}

Los servidores de \RStudio\ han sido ajustados en algunas escuelas para facilitar la computación basada en la nube.
\FoodForThought{Los servidores de \RStudio\ han sido instalados en muchas instituciones. Más detalles
acerca de licencias académicas (gratuitas) para 'RStudio Server Pro' como también instrucciones de ajuste se pueden encontrar en \url{http://www.rstudio.com/resources/faqs} en la viñeta {\tt Academic}
}

Una vez que se conecte al servidor, usted va ver una pantalla de inicio de sesión:
\FoodForThought{El servidor de \RStudio\ no suele funcionar bien con Internet Explorer}


\includegraphics[width=4.34in]{rstudio-login.png}

Una vez que se identifique, usted debería ver la interfaz de \RStudio\


\includegraphics[width=4.34in]{rstudio-init.png}

Observe que \Rstudio\ divide su universo en 4 paneles. 
Algunos de estos paneles después son subdivididos en viñetas múltiples. Qué viñetas aparecen en los paneles pueden ser personalizados por el usuario.
\R\ puede hacer muchísimo más que una simple calculadora, y vamos a introducir características 
adicionales en el debido tiempo. Sin embargo, hacer cálculos sencillos en \R\ es una
buena forma de iniciar el conocimiento de las características de \RStudio.

Los comandos ingresados en la ventana de la \tab{Consola} son inmediatamente ejecutados por \R.
AUna buena forma de familiarizarse con la consola es hacer algunos 
cálculos sencillos.  La mayoría de este trabajo lo podría esperar de una calculadora típica. Intente escribir los siguientes comandos en el panel de la consola:

<<arithmetic>>=
5 + 3
15.3 * 23.4
sqrt(16)                  # raíz cuadrada
@


Este último ejemplo demuestra como las funciones son llamadas dentro de \R\ como también el uso de comentarios
Los comentarios son anticipados por el símbolo \verb!#!.
Los comentarios pueden ser de mucha ayuda cuando se escriben scripts con múltiples comandos o para anotar código de ejemplo para sus estudiantes.

Usted puede guardar valores en variables nombradas para reutilización posterior.
\FoodForThought{Es probablemente mejor establecer el uso de uno u otro operador de asignación en lugar de estar cambiándolo. Personalmente preferimos el operador de la flecha, porque representa visualmente lo que está pasando en la asignación además porque deja clara la distinción entre el operador de asignación, el uso de \code{=}
en este caso es para dar valores a los argumentos de funciones, y el uso de \code{==} para probar la igualdad.}%

<<rs-variables1a,tidy=FALSE>>=
product = 15.3 * 23.4   # Guardar el resultado
product                 # Desplegar el resultado
product <- 15.3 * 23.4  # <- Puede ser utilizado 
                        #en lugar de =
product                     
@


Una vez que las variables son definidas, pueden ser referenciadas en otras operaciones y funciones.

<<rs-variables2,tidy=FALSE>>=
0.5 * product               # La mitad del producto
log(product)                # log (natural) del producto
log10(product)              # log base 10 del producto
log2(product)               # log base 2 del producto
log(product, base=2)        # log base 2 del producto, de otra forma
@

El punto y coma puede ser utilizado para ubicar comandos múltiples en una sola línea.  
Un uso frecuente de esto puede ser para salvar y después imprimir un valor, en una sola línea.

<<rs-variables-semi,tidy=FALSE>>=
product <- 15.3 * 23.4; product    # Salva el resultado y lo muestra
@


\subsection{Información de la versión}

\Rindex{sessionInfo()}%
\Rindex{RStudio.Version()}%
En algunos momentos, puede ser útil revisar qué versión del paquete \pkg{mosaic}, \R y \RStudio está usando. Ejecutando \function{sessionInfo()} se va desplegar información de R , los paquetes que están cargados y \function{RStudio.Version()} le proveerá información sobre la versión de \RStudio.

<<>>=
sessionInfo()
@


\section{Trabajando con archivos}

\subsection{Trabajando con archivos \R\ script}
Como alternativa, los comandos de \R\ pueden ser almacenados en un archivo. \RStudio\ ofrece un editor integrado para editar este tipo de documentos y facilita ejecutar algunos o todos los comandos. Para crear un archivo, seleccione en el menú de \RStudio\: \tab{File}, después \tab{New File}, después \tab{R Script}. Una ventana del editor de archivos se va abrir en el panel de \tab{Source}. El código de \R\ puede ser escrito ahí, y botones e ítems de menú son provistos para correr todo el código (llamado abastecer el documento) o ejecutar el código en una sola línea o en una sección seleccionada del documento. 

\subsection{Trabajando con RMarkdown, y knitr/\LaTeX}
Una tercera alternativa es tomar ventaja del apoyo que brinda \RStudio para la investigación reproducible. 
Si usted ya conoce \LaTeX, va a querer investigar las capacidades de \pkg{knitr}/\LaTeX.
Para aquellos que no conocen \LaTeX todavía, el sistema más sencillo de RMarkdown proporciona una entrada fácil en el mundo de los métodos de la investigación reproducible. Además brinda una buena estructura para que los estudiantes creen sus tareas y reportes que incluyen texto, código de \R, salidas de \R y gráficos.

Para crear un nuevo archivo de RMarkdown, seleccione la pestaña de \tab{File}, después \tab{New File}, después \tab{RMarkdown}. El archivo va ser abierto con un pequeño documento de plantilla que ilustra la especificación que tiene el lenguaje

\includegraphics[width=4.34in]{markdown1.png}

El paquete mosaic incluye dos plantillas útiles de RMarkdown para empezar: {\tt fancy} que es fina y exquisita (y esa era la intención, para dar una observación de las características) mientras que {\tt plain} es útil como un punto de inicio para un nuevo análisis. A estos se puede acceder usando la opción de {\tt Template} cuando se crea un nuevo archivo de RMarkdown.

\includegraphics[width=4.34in]{markdown2.png}


Presione el botón de \tab{Knit} para convertir a archivo HTML, PDF, o Word.

\includegraphics[width=4.34in]{markdown3.png}

Esto va generar una versión con formato del documento.

\includegraphics[width=4.34in]{markdown4.png}

Hay un botón (marcado con un signo de pregunta) que provee una pequeña descripción de las especificaciones del comando especificado. El sitio web de \RStudio\ incluye tutoriales más extensivos sobre la utilización de RMarkdown.

\Caution{Los archivosRMarkdown, and \pkg{knitr}/\LaTeX\ no tienen acceso al entorno de la consola, 
entonces el código debe ser autocontenido.}

%
Es importante recordar que contrario a los scripts de \R que son ejecutados en la consola y tiene acceso al entorno de la consola, los archivos de RMarkdown y \pkg{knitr}/\LaTeX no tienen acceso al entorno de la consola. Esto es una buena característica puesto que  obliga a los archivos a ser auto-contenidos, lo cual los hace transferibles y respeta las buenas prácticas de la investigación reproducible. Pero en el caso de los principiantes, especialmente si adoptan una estrategia de probar cosas en la consola, y copiar y pegar código de la consola en su documento, crean archivos que son incompletos y por esto no compilan correctamente.


\section{Otros paneles y viñetas}

\subsection{La viñeta de History(historial)}

Como los comandos son ingresados en la consola, así aparecen en la viñeta de \tab{History}. 
Estas "historias" o historiales pueden ser guardados y cargados, hay una opción de búsqueda para encontrar comandos previos, y líneas individuales previas o secciones pueden ser transferidas de vuelta a la consola. Mantener la viñeta de \tab{History} abierta le permite ir atrás y ver varios comandos anteriores. Esto puede ser especialmente útil cuando ciertos comandos producen una salida grande entonces la pantalla se mueve hacia abajo rápidamente.

\subsection{Comunicación entre viñetas}

\RStudio\ brinda varias formas de mover código de \R\ entre las viñetas. Presionar el botón de Run en el panel de edición para un script de \R\ o RMarkdown o algún otro documento va copiar líneas de código en la consola y ejecutarlas.

\subsection{La viñeta de files(archivos)}
La viñeta de \tab{Files} provee un manejador de datos simples. En esta se puede navegar de forma amigable y puede ser utilizada para abrir, renombrar y borrar archivos. En la versión de navegador web de RStudio, la pestaña de archivos también ofrece una utilidad para subir los archivos de la máquina local al servidor. En archivos de RMarkdown y \pkg{knitr} también se puede ejecutar código en algún "chunk" del archivo o en todos los "chunks" del archivo. Cada una de estas características simplifica el intentar escribir código "en vivo" mientras se crea un documento que deja un historial del código.

En la dirección inversa, el código del historial puede ser copiado de nuevo en la consola para ejecutarlo de nuevo (después de un poco de edición) o en una de las viñetas de edición, para la inclusión en un archivo.


\subsection{La viñeta de Help(ayuda)}
La viñeta de ayuda (\tab{Help}) es donde \RStudio\ despliega los archivos de ayuda de \R\. Se puede abrir un archivo de ayuda usando el operador \texttt{?} en la consola. Por ejemplo, el siguiente comando va mostrarnos el archivo de ayuda para la función de logaritmo.
<<eval=FALSE, tidy=FALSE>>=
?log
@

\subsection{La viñeta de Environment(entorno)}
La viñeta de entorno (\pkg{Environment}) muestra los objetos disponibles para la consola. Estos están subdivididos en datos, valores (no son objetos de tipo conjunto de datos, ni objetos de tipo función) y funciones. El ícono de la escoba puede ser utilizado para remover todos los objetos del entorno, y es bueno hacer esto de vez en cuando, especialmente cuando se está ejecutando RStudio en el servidor o si decide salvar el entorno cuando cierra RStudio, puesto que en estos casos los objetos se pueden quedar en el entorno indefinidamente.

\subsection{La viñeta de Plots(Gráficos)}
Los gráficos creados en la consola son desplegados en la viñeta de gráficos (\tab{Plots}). Por ejemplo, los siguientes comandos despliegan el número de nacimientos en Estados Unidos cada día en 1978.
<<message=FALSE, fig=TRUE>>=
# Esto va hacer los gráficos de lattice disponibles en la sesión
# Así como el set de datos Births78
require(mosaic)
xyplot(births ~ dayofyear, data=Births78)
@
En la viñeta de gráficos(\tab{Plots}), se puede navegar a gráficos anteriores y también exportar gráficos en varios formatos, después de interactivamente manipular las dimensiones.


% this fixes bad spacing -- but I don't know why the spacing was bad
%\bigskip
\subsection{La viñeta de Packages(paquetes)}

Mucha de la funcionalidad de \R\ está localizada en paquetes, muchos de los cuales se pueden obtener de la casa matriz llamada CRAN (Comprehensive R Archive Network). La viñeta de \tab{Packages} facilita instalar y cargar paquetes. También le permite buscar paquetes que han sido actualizados desde que usted los instaló.

\chapter{Una variable cuantitativa}

\section{Resúmenes numéricos}

\R\ incluye comandos para resumir variables numéricamente. Estos incluyen la capacidad de calcular la media, la desviación estándar, la varianza, mediana, el mínimo, máximo el primer cuartil, el tercer cuartil, el rango intercuartil así como cuartiles arbitrarios. Esto lo ilustraremos usando la medida de síntomas depresivos (que toma valores entre 0 y 60, con notas mayores indicando mayores síntomas depresivos) del CESD (Center for Epidemiologic Studies--Depression).

Para mejorar la legibilidad de las salidas, también vamos a elegir una cantidad de números predeterminados para desplegar el resultado de forma más razonable (vea \function{?options} para un mayor número de configuraciones posibles).

\myindex{HELPrct dataset}%
\Rindex{options()}%
\Rindex{require()}%
\Rindex{mosaic package}%
<<cesd1,cache=FALSE>>=
require(mosaic)
require(mosaicData)
options(digits=4)
mean(~ cesd, data=HELPrct)
@

\myindex{Start Teaching with R@\emph{Start Teaching with R}}%
\myindex{Teaching with R@\emph{Teaching with R}}%
\myindex{Start Modeling with R@\emph{Start Modeling with R}}%
\myindex{Modeling with R@\emph{Modeling with R}}%
Note que \function{mean}, dentro del paquete \pkg{mosaic} utiliza la notación de fórmula de los gráficos lattice comunes y los modelos lineales (e.g lm()). El paquete mosaic permite que muchas otras funciones utilicen la misma notación, la cual vamos a estar utilizando a lo largo de este documento.  
\DiggingDeeper[-3cm]{Si usted no ha visto la notación de fórmula antes de este libro, \emph{Empiece a enseñar con R} lo presenta una detalladamente. \emph{Start Modeling with R}, otro libro, detalla la relación entre el proceso de modelaje y la notación de la fórmula. }

\Rindex{with()}%
\Rindex{mean()}%
La misma salida puede ser creada utilizando los siguientes comandos (sin embargo, nosotros utilizaremos la version de MOSAIC cuando sea posible)
<<>>=
with(HELPrct, mean(cesd))
mean(HELPrct$cesd)
@
\Rindex{sd()}%
\Rindex{var()}%
La misma funcionalidad existe para otras estadísticas de resumen
<<cesd2,cache=FALSE>>=
sd(~ cesd, data=HELPrct)
@
<<cesd2b,cache=FALSE>>=
sd(~ cesd, data=HELPrct)^2
var(~ cesd, data=HELPrct)
@

Es también muy sencillo calcular cuartiles de la distribución

\myindex{quantiles}%
\Rindex{median()}%
<<cesd3>>=
median(~ cesd, data=HELPrct)
@

Como predeterminado, la función \function{quantile} muestra los cuartiles, pero se le puede dar un vector de cuantiles a desplegar.

\Rindex{quantile()}%
\Caution{No todos los comandos han sido actualizados para utilizar la notación de fórmula. Para estas variables se debe acceder a los conjuntos de datos con la función \function{with}}
<<cesd4>>=
with(HELPrct, quantile(cesd))
with(HELPrct, quantile(cesd, c(.025, .975)))
@

\hfill

\Rindex{favstats()}%
Finalmente, la función \function{favstats} en el paquete \pkg{mosaic}, muestra un resumen conciso de estadísticas descriptivas útiles.
<<>>=
favstats(~ cesd, data=HELPrct)
@

\section{Resúmenes gráficos}
La función \function{histogram} es utilizada para crear un histograma. Aquí utilizamos la notación de fórmula (como se discutió en el libro \emph{Start Modeling with R}) para especificar que queremos un histograma de los puntajes del CESD

\Rindex{histogram()}%
\vspace{-4mm}
\begin{center}
<<cesd-hist>>=
histogram(~ cesd, data=HELPrct)
@
\end{center}

Podemos usar las opciones de \function{width} y \function{center} para controlar la ubicación y tamaño de las barras.

\begin{center}
<<cesd-hist2>>=
histogram(~ cesd, width=5, center=2.5, data=HELPrct)
@
\end{center}


\Rindex{tally()}%
\Rindex{format option}%
En el conjunto de datos \variable{HELPrct}, aproximadamente un cuarto de los sujetos son mujeres.  
<<>>=
tally(~ sex, data=HELPrct)
tally(~ sex, format="percent", data=HELPrct)
@

Directamente vamos a restringir nuestra atención a únicamente los sujetos femeninos. Si vamos a hacer una gran cantidad de cosas con una parte de nuestro conjunto de datos,  lo más sencillo puede ser hacer un nuevo conjunto de datos conteniendo sólo los casos en los que estamos interesados. La función \function{filter()} en el paquete \pkg{dplyr} puede ser utilizada para generar una nueva tabla de datos que contiene solamente los hombres o las mujeres (observar la sección 13.5). Una vez que esto sea creado, la función \function{stem} es utilizada para crear un diagrama de tallo y hojas.
\Caution{Note que el operador para igualdad utiliza \emph{dos} signos de igual.}
\Rindex{stem()}%
\Rindex{filter()}%
\Rindex{dplyr package}%
<<cesd-stem>>=
female <- filter(HELPrct, sex=='female')
male <- filter(HELPrct, sex=='male')
with(female, stem(cesd))
@

\Rindex{dplyr package}%
\Rindex{tidyr package}%

Los subconjuntos de datos también pueden ser generadas y utilizadas "a medio camino" (esta vez lo veremos traslapando la densidad normal):
\Rindex{fit option}%
<<women-cesd-hist,tidy=FALSE,message=FALSE, fig=TRUE>>=
histogram(~ cesd, fit="normal",
  data=filter(HELPrct, sex=='female'))  
@

Alternativamente podemos hacer gráficos uno al lado del otro para comparar múltiples subconjuntos:
<<cesd-male-female, fig=TRUE>>=
histogram(~ cesd | sex, data=HELPrct)
@

La estructura puede ser reacomodada
\Rindex{layout option}%
\begin{center}
<<cesd-dotlayout, fig=TRUE>>=
histogram(~ cesd | sex, layout=c(1, 2), data=HELPrct)   
@
\end{center}

Podemos controlar el número de barras de varias formas. Esto puede ser especificado mediante 
el número total
\Rindex{nint option}%
\begin{center}
<<cesd-dot,fig.height=1.8>>=
histogram(~ cesd, nint=20, data=female)   
@
\end{center}
El ancho de las barras puede ser especificado
\Rindex{width option}%
\begin{center}
<<cesd-dotwidth,fig.height=1.8, fig=TRUE>>=
histogram(~ cesd, width=2, data=female)   
@
\end{center}

La función \function{dotPlot} es utilizada para crear un gráfico de puntos de pequeños grupos de sujetos (mujeres indigentes). También demostramos como cambiamos el nombre del eje X.
\Rindex{dotPlot()}%
<<cesd-dot4,tidy=FALSE, fig=TRUE>>=
dotPlot(~ cesd, xlab="Nota del CESD", 
  data=filter(HELPrct, (sex=="female") & (homeless=="homeless")))
@


\section{Curvas de densidad}

\FoodForThought{Los gráficos de densidad también son sensibles a ciertas opciones. Si su gráfico de densidad es demasiado irregular o demasiado suavizado, intente cambiar el argumento adjust : más largo que 1 para gráficos demasiado suavizados, menos de 1 para gráficos sumamente irregulares.} Una desventaja de los histogramas es que pueden ser sensibles a la elección del número de barras. Otro tipo de gráficos a considerar es la curva de densidad.

Aquí adornamos el gráfico de densidad con algunas adiciones para demostrar cómo se construye un gráfico para propósitos pedagógicos. Le agregamos algún texto, una función de densidad normal superimpuesta así como una línea vertical. Una variedad de tipos de líneas y colores pueden ser especificados, así como anchos.

\DiggingDeeper{La función \function{plotFun} puede también utilizarse para anotar gráficos (ver sección 10.2.1)}
\begin{center}
\Rindex{densityplot()}%
\Rindex{ladd()}%
\Rindex{panel.mathdensity()}%
\Rindex{panel.abline()}%
\Rindex{col option}%
\Rindex{grid.text()}%
\Rindex{lty option}%
\Rindex{lwd option}%
<<dens1,tidy=FALSE,fig.keep="last", fig=TRUE>>=
densityplot(~cesd, data=female);ladd(grid.text(x=0.2, y=0.8, 'solo mujeres'));ladd(panel.mathdensity(args=list(mean=mean(cesd), sd=sd(cesd)), col="red"), data=female);ladd(panel.abline(v=60, lty=2, lwd=2, col="grey"))
@
\end{center}

\section{Polígonos de frecuencia}
\myindex{polygons}%

Una tercera opción es un polígono de frecuencias, donde el gráfico es creado uniendo los puntos medios en la parte superior de las barras de un histograma.
\Rindex{freqpolygon()}%
\begin{center}
<<poly,tidy=FALSE,fig.keep="last",out.width="2.5in", fig=TRUE>>=
freqpolygon(~ cesd, data=female)
@
\end{center}

\section{Distribuciones normales}

\FoodForThought{\code{x} es de eXtra.}%
La curva de densidad más famosa es la distribución normal. La función \function{xpnorm} despliega la probabilidad de que una variable aleatoria sea menor que el primer argumento, para una distribución normal con una media dada en el segundo argumento y con la desviación estándar de tercer argumento. Más información sobre las distribuciones de probabilidad se puede encontrar en la sección 11.
<<norm1,fig.width=5,fig.height=2.4>>=
xpnorm(1.96, mean=0, sd=1)
@


\section{Inferencia para una sola muestra}
\label{sec:bootstrapsing}

\Rindex{t.test()}%
\Rindex{confint()}%

Podemos calcular un intervalo de confianza para el 95\% de confianza para la media de puntuación del CESD para mujeres 

usando la prueba t
<<tinterval>>=
t.test(~ cesd, data=female)
confint(t.test(~ cesd, data=female))
@

\DiggingDeeper{More details and examples can be found in the 
\pkg{mosaic} package Resampling Vignette.}
\myindex{bootstrapping}%
\myindex{resampling}%
Sin embargo, esto también puede observarse usando bootstrap. 
El estadístico que queremos remuestrear es la media
<<calculuatemean>>=
mean(~ cesd, data=female)
@

One resampling trial can be carried out:
\FoodForThought{Aquí se muestrea con remplazo de la tabla de datos original, creando una tabla de datos remuestreada con el mismo número de filas.}
\Rindex{resample()}%
<<resamplemean>>=
mean(~ cesd, data=resample(female))
@
\FoodForThought{Aunque un único intento es de poco uso, es inteligente hacer a los estudiantes calcular para mostrarle que están (usualmente) consiguiendo un resultado diferente que el que se obtiene sin remuestreo}

Otro generará un resultado diferente:
<<>>=
mean(~ cesd, data=resample(female))
@

Ahora haremos 1000 remuestreos, guardando el resultado en un objeto llamado trials:
called \texttt{trials}:
\Rindex{do()}%
\Rindex{qdata()}%
<<bootint>>=
trials <- do(1000) * mean(~ cesd, data=resample(female))
head(trials, 3)
qdata(~ mean, c(.025, .975), data=trials)
@


\chapter{Una variable categóricas}
\section{Resúmenes numéricos}

\myindex{categorical variables}
\myindex{contingency tables}
\myindex{tables}

\DiggingDeeper{El libro \emph{Empiece a enseñar con R} introduce la notación de fórmula utilizada alrededor de este libro. Vea también \emph{Empiece a enseñar con R} para conexiones al modelaje estadístico..}

La función \function{tally} puede ser utilizada para calcular conteos, porcentajes y proporciones para variables categoricas.

\Rindex{tally()}%
\Rindex{margins option}%
<<homeless-table>>=
tally(~ homeless, data=HELPrct)      
tally(~ homeless, margins=TRUE, data=HELPrct)      
tally(~ homeless, format="percent", data=HELPrct)      
tally(~ homeless, format="proportion", data=HELPrct)  
@

\section{La prueba binomial}

\myindex{binomial test}%
\Rindex{binom.test()}%
Un intervalo de confianza exacto para la proporción (así como una prueba de hipótesis para que la proporción sea igual a un valor particular [predeterminado 0.5]) puede ser calculado usando la función \function{binom.test}. El estándar de \function{binom.test()} requiere que tabulemos
<<>>=
binom.test(209, 209 + 244)
@
El paquete \pkg{mosaic} utiliza la notación de fórmula que evita la necesidad de pre-tabular los datos.
<<binomtest>>=
result <- binom.test(~ (homeless=="homeless"), data=HELPrct)
result
@

Como es generalmente con este tipo de comandos, hay una cantidad de resultados disponibles del objeto devuelto por la función.
<<>>=
names(result)
@
Estos pueden ser extraídos usando el operador {\tt \$} o un extractor de la función. Por ejemplo, el usuario puede extraer el intervalo de confianza o el p-value.
\Rindex{confint()}%
\Rindex{pval()}%
\Rindex{print()}%
<<binomtest2>>=
result$statistic
confint(result)
pval(result)
@
\DiggingDeeper{La mayoría de objetos en R tiene un método de impresión o \function{print()}. Entonces cuando conseguimos el resultado, lo que hacemos es ver desplegado en la consola el \code{print(resultado)}. Por lo que puede haber una cantidad buena de información escondiéndose en el objeto mismo.
En algunas situaciones, así como los gráficos, los objetos son devueltos \emph{invisiblemente}, entonces nada se imprime. Eso evita que tenga que ver una salida no deseada para consumo humano. Usted de todos modos puede asignar el objeto devuelto a una variable y procesarlo más tarde, incluso si nada aparece en la pantalla. Esto en ocasiones es útil para las funciones gráficas de \pkg{lattice}.}%

\section{La prueba de la proporción}

Un intervalo y prueba similar pueden ser calculados usando la función \function{prop.test()}. 
\Rindex{prop.test()}%
\Rindex{correct option}%
Aquí está una cuenta del número de personas a cada uno de los dos niveles de la variable \variable{homeless}.

<<tidy=FALSE>>=
tally(~ homeless, data=HELPrct)
@

La función de \function{prop.test()} va a llevar a cabo los cálculos de la prueba de la proporción y reporta el resultado.

\hfill

<<tidy=FALSE>>=
prop.test(~ (homeless=="homeless"), correct=FALSE, data=HELPrct)
@
En esta declaración, \function{prop.test()} está examinando la variable homeless en la misma forma que \function{tally()} lo haría. \Pointer{Escribimos \code{homeless=="homeless"} para definir de forma no ambigua que proporción estamos considerando. Podríamos haber escrito también \code{homeless=="housed"}. }
\function{prop.test} también puede trabajar directamente con conteos numéricos, de la forma que \function{binom.test()} lo hace.
\InstructorNote{\function{prop.test()} calcula un estadístico Ji-cuadrado. La mayoría de textos introductorios usan un estadístico z, son matemáticamente equivalentes en terminos de las inferencias, pero tal vez necesite mostrarle esta discrepancia a los estudiantes}%
<<>>=
prop.test(209, 209 + 244, correct=FALSE)
@

\section{Bondad de ajuste}

Una variedad de pruebas de bondad de ajuste pueden ser calculadas para una distribución dada. Para los datos de HELP, podemos probar la hipótesis nula de que la proporción de sujetos en cada grupo de abuso de sustancias es igual en la población original.

<<gofmore,tidy=FALSE>>=
tally(~ substance, format="percent", data=HELPrct)
observed <- tally(~ substance, data=HELPrct)
observed
@

\Caution[-1cm]{Además de las opción de \option{format}, hay una opción de incluir los marginales, para incluir el marginal de los totales en la tabla. El predeterminado en \function{tally()} es \option{margins=FALSE}. ¡Inténtelo!}
\Rindex{chisq.test()}%
<<tidy=FALSE>>=
p <- c(1/3, 1/3, 1/3)   # equivalente a rep(1/3, 3)
chisq.test(observed, p=p)
total <- sum(observed); total
expected <- total*p; expected
@

También podemos calcular el estadístico $\chi^2$ como la función observada y los valores esperados.

\Rindex{sum()}%
\Rindex{pchisq()}%
<<gof2,tidy=FALSE>>=
chisq <- sum((observed - expected)^2/(expected)); chisq
1 - pchisq(chisq, df=2)
@
\FoodForThought[-2cm]{La función \function{pchisq} calcula la probabilidad de que una variable aleatoria $\chi^2$ con \function{df()} grados de libertad es menor o igual al valor dado. Aquí calculamos el complemento para encontrar el área al derecho del valor observado del estadístico Chi-cuadrado.}%

Puede ser útil consultar un gráfico del estadístico, donde el área sombreada representa el valor de la derecha del valor observado.

\Rindex{plotDist()}%
<<chisqplotDist>>=
plotDist("chisq", df=2, groups = x > 9.31, type="h")
@


Alternativamente, el paquete \pkg{mosaic} ofrece una versión del \function{chisq.test()} con una salida "más rellena"
\Rindex{xchisq.test()}%
<<>>=
xchisq.test(observed, p=p)
@
\FoodForThought[-1.5cm]{\code{x} en \function{xchisq.test} significa eXtra}

\FoodForThought{Objetos en el espacio de trabajo son listados en la viñeta de {\sc Entorno (Environment)} en \RStudio. Si usted quiere limpiar un poco la lista, remueva los objetos que ya no neecesita con \function(rm()).}
<<>>=
# limpiar las variables que ya no son necesarias
rm(observed, p, total, chisq)  
@

\chapter{Dos variables cuantitativas}

\section{Gráficos de dispersión}
\myindex{scatterplots}%
\myindex{lowess}%
\myindex{smoothers}%
\myindex{linearity}%

Siempre motivamos a nuestros estudiantes a iniciar cualquier análisis mediante la graficación de sus datos. Aquí presentamos un gráfico de dispersión de la CESD (una medida de síntomas depresivos, mayores puntuaciones indican mayor cantidad de síntomas) y el MCS (Puntuación del componente mental del SF-36, donde las puntuaciones mayores indican mejor funcionamiento) para los sujetos femeninos con una línea lowess (loess en español, una línea de regresión local), usando círculos como la figura para los puntos y una línea un poco más gruesa.

\InstructorNote{La línea lowess puede ayudar a evaluar la linealidad de la relación. Esto es especificando en la función ambos puntos (usando 'p') y el suavizador lowess.}
\Rindex{xyplot()}%
\Rindex{pch option}%
\Rindex{cex option}%
\Rindex{lwd option}%
\Rindex{type option}%
\begin{center}
<<HELPrct-xyplot,fig.height=3,tidy=FALSE, fig=TRUE>>=
require(mosaicData)
females <- filter(HELPrct, female==1)
xyplot(cesd ~ mcs, type=c("p","smooth"), pch=1, 
  cex=0.6, lwd=3, data=females)
@
\end{center}
\DiggingDeeper{El libro \emph{Start Modelling with R} da a mayor profundidad como se utiliza el lenguaje para modelar. \emph{Empiece a enseñar con R} también brinda una guía útil para entenderlo}

Con esto es sencillo poder agregar algo más que símbolos en el gráfico de dispersión. En este ejemplo, el conjunto de datos de \dataframe{USArrest} puede ser utilizado para graficar la asociación entre los índices de asalto y asesinato, con el nombre del estado. Esto requiere una función de panel.
\Rindex{function()}%
\Rindex{panel.labels()}%
\Rindex{panel.text()}%
\Rindex{rownames()}%
<<tidy=FALSE, fig=TRUE>>=
panel.labels <- function(x, y, labels='x',...) { 
  panel.text(x, y, labels, cex=0.4, ...)
}
xyplot(Murder ~ Assault, panel=panel.labels, 
  labels=rownames(USArrests), data=USArrests)
@


\vspace*{-1cm}

\section{Correlación}


Las correlaciones pueden ser calculadas para un par de variables o para una matriz de variables.
\myindex{correlation}%
\Rindex{cor()}%
<<>>=
cor(females$cesd, females$mcs)
smallHELP <- select(females, cesd, mcs, pcs)
cor(smallHELP)
@
\myindex{Pearson correlation}%
\myindex{Spearman correlation}%

Como predeterminado, la correlación de Pearson es la que se muestra. Otras variables (ejemplo, Spearman) pueden ser especificadas usando la opción de method
\option{method} option.
<<>>=
cor(females$cesd, females$mcs, method="spearman", data=females)
@

\section{Pairs plots}
\myindex{pairs plot}%
\myindex{scatterplot matrix}%

Los pares de gráficos (matrices de gráficos de dispersión) pueden ser calculados para cada par de un set de variables.
\FoodForThought{El paquete \pkg{GGally} ofrece una opción para gráficos de pares más elaborados.}
\Rindex{splom()}%
<<fig.height=3, fig=TRUE>>=
splom(smallHELP, cex=0.3)
@

\section{Regresión lineal simple}

\InstructorNote{Tenemos la tendencia a introducir la regresión lineal de manera pronta en nuestros cursos, como una técnica simplemente descriptiva.}
\myindex{linear regression}%
\myindex{regression}%

Los modelos de regresión lineal simple son descritos en detalle en Start Modeling with R. Estos usan con la misma notación de fórmula introducida con anterioridad para resúmenes numéricos y gráficos, especificando la respuesta y los predictores. Aquí consideraremos ajustar el modelo \model{\variable{cesd}{\variable{mcs}}}


\Rindex{lm()}%
\Rindex{coef()}%
<<>>=
cesdmodel <- lm(cesd ~ mcs, data=females)
coef(cesdmodel)
@
\InstructorNote{Es importante escoger buenos nombres para objetos de tipo modelo. Aquí la salida de \function{lm} es guardada como \code{cesdmodel}, que denota que es un modelo de regresión a las puntuaciones de síntomas de depresión}

Para simplificar la salida, desactivamos la opción de desplegar las estrellas de significancia.

\myindex{significance stars}%
\Rindex{msummary()}%
\Rindex{confint()}%
\Rindex{rsquared()}%
\Rindex{coef()}%
<<>>=
options(show.signif.stars=FALSE)
coef(cesdmodel)
msummary(cesdmodel)
coef(summary(cesdmodel))
confint(cesdmodel)
rsquared(cesdmodel)
@
\Rindex{class()}%
<<lmclass>>=
class(cesdmodel)
@
La salida de un \function{lm} es un objeto de modelo lineal. Hay unas cuantas funciones que pueden operar estos objetos, como se vio previamente con \function{coef}. La función \function{residuals} devuelve un vector de residuales
\Rindex{residuals()}%
\FoodForThought{La función \function{residuals} puede ser abreviada \function{resid}. Otra función útil es \function{fitted}, que muestra un vector de los valores predichos.}


\Rindex{density option}%
\begin{center}
<<lmhist>>=
histogram(~ residuals(cesdmodel), density=TRUE)
@
\end{center}
\Rindex{qqmath()}%
\begin{center}
<<HELPrct-resid-qq, fig=TRUE>>=
qqmath(~ resid(cesdmodel))
@
\end{center}
\Rindex{alpha option}%
\begin{center}
<<HELPrct-resid-plot, fig=TRUE>>=
xyplot(resid(cesdmodel) ~ fitted(cesdmodel), 
       type=c("p", "smooth", "r"), 
       alpha=0.5, cex=0.3, pch=20)
@
\end{center}

La función \function{mplot} puede facilitar crear una variedad de gráficos útiles, incluyendo los gráficos de dispersión de residuales y ajustados, especificando la opción (\option{which=1}).
\Rindex{mplot()}%
\Rindex{which option}%
<<mplotc1, fig=TRUE>>=
mplot(cesdmodel, which=1)
@

También puede generar un gráfico cuantilo-cuantilo para una distribución normal (\option{which=2}),
<<mplotc2, fig=TRUE>>=
mplot(cesdmodel, which=2)
@

\myindex{scale versus location}%
Un gráfico de escala y locación,
<<mplotc3, fig=TRUE>>=
mplot(cesdmodel, which=3)
@

\myindex{Cook's distance}%
Distancia de Cook por número de observación,
<<mplotc4, fig=TRUE>>=
mplot(cesdmodel, which=4)
@

\myindex{leverage}%
residuals vs.\,leverage,
<<mplotc5, fig=TRUE>>=
mplot(cesdmodel, which=5)
@


\chapter{Dos variables categóricas}

\section{Tablas de clasificación cruzada (o de contingencia)}
\label{sec:cross}

\myindex{cross classification tables}%
\myindex{contingency tables}%
\myindex{tables}%

Las tablas de clasificaciones cruzadas (two-way o $R$ por $C$) pueden ser construidas para una (o más) variables categóricas. Aquí consideramos la tabla de contingencia para el status de homeless (sin casa por una o más noches en los últimos 6 meses o con casa) y sexo.

<<homeless-sex>>=
tally(~ homeless + sex, margins=FALSE, data=HELPrct)     
@

También podemos calcular los porcentajes de columna.
\Rindex{tally()}%
<<homeless-sex-row,tidy=FALSE>>=
tally(~ sex | homeless, margins=TRUE, format="percent", 
  data=HELPrct)     
@

Podemos calcular el radio de propensión (odds ratio) directamente de la tabla:
<<tidy=FALSE>>=
OR <- (40/169)/(67/177); OR
@

El paquete \pkg{mosaic} tiene una función que calcula el radio de propensión:
\Rindex{oddsRatio()}%
<<tidy=FALSE>>=
oddsRatio(tally(~ (homeless=="housed") + sex, margins=FALSE, 
  data=HELPrct)) 
@

La función \function{CrossTable} en el paquete \pkg{gmodels} también despliega una tabla de clasificación cruzada.

\Rindex{CrossTable()}%
<<crosstable, message=FALSE>>=
require(gmodels)
with(HELPrct, CrossTable(homeless, sex, 
  prop.r=FALSE, prop.chisq=FALSE, prop.t=FALSE))
@

Los resúmenes gráficos de las tablas de clasificación cruzada pueden ser útiles para visualizar asociaciones. Los gráficos de mosaic son un ejemplo, donde el total (todas las observaciones) es proporcional a uno.
\Caution{El jurado está aún preocupado de la utilidad de los gráficos de mosaic (también conocidos como eikosograms) en cuanto a la presentación de gráficos con pocos datos. Hemos encontrado gran ayuda en ellos para mejorar el entendimiento de una tabla de contingencia de dos vías.\cite{Tufte:2001:Visual}}%
Aquí, vemos como los hombres tienden a ser sobrepresentados entre los sujetos sin casa (como se representa en la línea horizontal, la cual es mayor para los sin casa que para los con casa)

\FoodForThought{La función \function{mosaic()} en el paquete \pkg{vcd} también hace gráficos mosaic}
\Rindex{mosaicplot()}%
\begin{center}
<<mosaicplot,fig.height=3.5,tidy=FALSE, fig=TRUE>>=
mytab <- tally(~ homeless + sex, margins=FALSE, 
  data=HELPrct)
mosaicplot(mytab)
@
\end{center}

\section{Creando tablas de resumen de estadísticas}

Las tablas pueden ser creadas para estadísticas de resumen usando la función \function{do}.

<<>>=
HELPtable <- rbind(
  do(40)  * data.frame(sex="female", homeless="homeless"),
  do(169) * data.frame(sex="male",   homeless="homeless"),
  do(67)  * data.frame(sex="female", homeless="housed"),
  do(177) * data.frame(sex="male",   homeless="housed")
)
tally(~ homeless + sex, data=HELPtable)
@

\section{Pruebas de ji-cuadrado}

\Rindex{chisq.test()}%
<<chisq1,tidy=FALSE>>=
chisq.test(tally(~ homeless + sex, margins=FALSE,
  data=HELPrct), correct=FALSE)
@

Encontramos una asociación estadística significativa: es poco verosímil que observáramos una asociación así de fuerte si el estado de vivir en una casa y el sexo fueran independientes en la población

Cuando los estudiantes descubren una asociación significativa, es importante que sean capaces de interpretar en el contexto del problema. La función \function{xchisq.test} proporciona detalles adicionales (observados, esperados, contribución al estadístico y residual) para ayudar en este proceso.
\FoodForThought{\code{x} es de eXtra.}

\Rindex{xchisq.test()}%
<<chisq2,tidy=FALSE>>=
xchisq.test(tally(~homeless + sex, margins=FALSE,
  data=HELPrct), correct=FALSE)
@

Aquí observamos que hay menos mujeres indigentes, y más hombres de los que se esperaría. 

\section{Prueba exacta de Fisher}
\myindex{Fisher's exact test}%

Una prueba exacta de Fisher puede también ser calculada. Este cálculo está dirigido a tablas de 2 por 2. Existen opciones para solventar el problema del límite de tamaño para tablas más grandes (vea \function{?fisher.test()}).

\DiggingDeeper{Note la diferencia en el estimado del radio de propensión del visto en la sección 6.1. La función \function{fisher.test} usa un estimador diferente (y un intervalo diferente en el perfil de la verosimilitud).}
\Rindex{fisher.test()}%
<<help-fisher,tidy=FALSE>>=
fisher.test(tally(~homeless + sex, margins=FALSE,
  data=HELPrct))
@

\chapter{Respuesta cuantitativa, predictor categórico}

\section{Un predictor dicotomico: resúmenes gráficos y numéricos} 
Aquí vamos a comparar las distribuciones de las puntuaciones de CESD por sexo. La función \function{mean()} puede usarse para calcular la media del puntaje de CESD separado para hombres y mujeres.
\Rindex{mean()}%
<<aggregate>>=
mean(cesd ~ sex, data=HELPrct)
@
\Rindex{favstats()}%
La función \function{favstats()} puede mostrar más estadísticas por grupo.

<<summary>>=
favstats(cesd ~ sex, data=HELPrct)
@


Los diagramas de cajas son una presentación gráfica particularmente útil para comparar distribuciones. La función \function{bwplot} puede ser utilizada para desplegar los diagramas de cajas de los puntajes de \variable{CESD} separados por sexo. Vemos de ambos resúmenes, numérico y gráfico, que las mujeres tienden a tener un puntaje un poco mayor en el \variable{CESD} que los hombres.

\FoodForThought[-3cm]{Aunque usualmente ponemos variables explicatorias alrededor del eje horizontal, en ocasiones el ajuste de la página la envia a otra orientación preferible en estos gráficos}
%\vspace{-8mm}
\Rindex{bwplot()}%
\begin{center}
<<cesd-box,fig.height=1.5, fig=TRUE>>=
bwplot(sex ~ cesd, data=HELPrct)
@
\end{center}

Cuando los tamaños de muestra son pequeños, no hay razón para resumirlos con un diagrama de cajas puesto que \function{xyplot} puede manejar predictores categóricos. Incluso con 10-{20 observaciones en un grupo, un gráfico de dispersión es bastante entendible. Ajustar un valor del nivel de alpha ayuda a detectar observaciones múltiples con el mismo valor.
\FoodForThought{Una vez, uno de nosotros vio a un biólogo presentar orgullosamente unos diagramas de caja de lado a lado. Pensando que esta era una victoria mayor, inocentemente se le preguntó cuántas observaciones había en cada grupo: "cuatro" respondió el biólogo.}
\Rindex{xyplot()}%
\Rindex{alpha option}%
\Rindex{cex option}%
\begin{center}
<<KidsFeet-xy,fig.height=1.5, fig=TRUE>>=
xyplot(sex ~ length, alpha=.6, cex=1.4, data=KidsFeet) 
@
\end{center}

\section{Un predictor dicotómico: t de dos muestras}

La prueba de dos muestras de Student puede ser ejecutada sin (predeterminada) asumir o asumiendo una igualdad de varianza.
\Rindex{t.test()}%
\Rindex{var.equal option}%
<<HELPrct-nonpar,tidy=FALSE>>=
t.test(cesd ~ sex, var.equal=FALSE, data=HELPrct)
@
Podemos ver que hay una diferencia significativa entre dos grupos.

Podemos repetirla suponiendo igualdad de varianzas.
<<tidy=FALSE>>=
t.test(cesd ~ sex, var.equal=TRUE, data=HELPrct)
@

Los grupos pueden ser comparados también utilizando la función \function{lm()} (también bajo el supuesto de igualdad). El comando de mosaic \function{msummary()} ofrece una versión un poco más tersa de la salida típica de \function{summary()}
\Rindex{msummary()}%
\Rindex{summary()}%
<<>>=
msummary(lm(cesd ~ sex, data=HELPrct))
@

\FoodForThought[1cm]{La función \function{lm()} es parte de una estructura más flexible de modelaje, mientras el \function{t.test()} es fundamentalmente una calle sin salida. \function{lm()} usa el supuesto de la igualdad de varianza. Vea el libro, \emph{Start Modeling in R} para más detalles. .}%


\section{Prueba de 2 grupos no paramétrica}

La misma conclusión puede ser obtenida usando una prueba no parametrica (suma de rangos de Wilcoxon).

\Rindex{wilcox.test()}%
<<HELPrct-nonpar2>>=
wilcox.test(cesd ~ sex, data=HELPrct)
@


\section{La prueba con la permutación}
\myindex{resampling}%
\myindex{permutation test}%


Aquí, extendemos los métodos introducidos en la sección 3.6 para llevar a cabo una prueba de dos colas comparando las edades por género. Primero, calculamos la diferencia observada en las medias
\Rindex{diffmean()}%
\Rindex{shuffle()}%
<<>>=
mean(age ~ sex, data=HELPrct)
test.stat <- diffmean(age ~ sex, data=HELPrct)
test.stat
@
Podemos calcular el mismo estadístico después de mezclar los niveles de los grupos:
<<>>=
do(1) * diffmean(age ~ shuffle(sex), data=HELPrct)
do(1) * diffmean(age ~ shuffle(sex), data=HELPrct)
do(3) * diffmean(age ~ shuffle(sex), data=HELPrct)
@

\DiggingDeeper{Más detalles pueden ser encontrados en el paquete \pkg{mosaic}, Resampling vignette}
\Rindex{xlim option}%
\Rindex{groups option}%
<<permute-HELPrct,fig.keep='last', tidy=FALSE, fig=TRUE>>=
rtest.stats <- do(500) * diffmean(age ~ shuffle(sex), 
  data=HELPrct)
head(rtest.stats, 3)
favstats(~ diffmean, data=rtest.stats)
histogram(~ diffmean, n=40, xlim=c(-6, 6),
  groups=diffmean >= test.stat, pch=16, cex=.8, 
  data=rtest.stats)
ladd(panel.abline(v=test.stat, lwd=3, col="red"))
@

Aquí no vemos mucha evidencia que contradiga la hipotesis nula de que los hombres y las mujeres tienen la misma media de edad en la población.

\section{Análisis de varianza de una vía}
\myindex{one-way ANOVA}%
\myindex{analysis of variance}%

Las primeras comparaciones fueron entre dos grupos. Podemos también considerar probar las diferencias entre tres o más grupos usando un ANOVA de una vía. Aquí vamos a comparar los puntajes de \variable{CESD} por sustancia primaria de abuso (heroína, cocaína o alcohol) con una línea en lugar de un punto para indicar la mediana.

\Rindex{bwplot()}%
\begin{center}
<<cesd-oneway,fig.width=6,fig.height=1.9, fig=TRUE>>=
bwplot(cesd ~ substance, pch="|", data=HELPrct)
@
\end{center}



<<aggregate2>>=
mean(cesd ~ substance, data=HELPrct)
@
\Rindex{aov()}%
<<help-aov>>=
anovamod <- aov(cesd ~ substance, data=HELPrct)
summary(anovamod)
@
Aunque las puntuaciones todavía altas (puntajes de 16 o más son generalmente considerados como síntomas "severos"), el grupo envuelto en cocaína tiende a tener los puntajes más bajos que aquellos cuya sustancia primaria es el alcohol o la heroína.
<<help-aovlm>>=
modintercept <- lm(cesd ~ 1, data=HELPrct)
modsubstance <- lm(cesd ~ substance, data=HELPrct)
@

El comando \function{anova()} puede resumir los modelos.
\Rindex{anova()}%
<<>>=
anova(modsubstance)
@

En este caso los resultados son idénticos (puesto que solo tenemos un predictor, con 2 grados de libertad)

La función \function{anova()} puede también ser utilizada para formalmente comparar dos modelos (anidados).
\myindex{model comparison}%
<<help-aov-more>>=
anova(modintercept, modsubstance)
@


\section{Las diferencias significativas honestas de Tukey}
\myindex{Tukey's HSD}%
\myindex{honest significant differences}%
\myindex{multiple comparisons}%

Hay una variedad de procedimientos de comparaciones múltiples que pueden ser utilizados después de ajustar el modelo ANOVA. Una de estas son las Diferencias significativas honestas de Tukey (HSD por las siglas en inglés). Otras opciones están disponibles dentro del paquete \pkg{multcomp}.

<<help-hsd>>=
favstats(cesd ~ substance, data=HELPrct)
@
\Rindex{TukeyHSD()}%
\Rindex{factor()}%
\Rindex{levels option}%
\Rindex{labels option}%
\Rindex{mutate()}%
\Rindex{lm()}%
<<help-hsd2,tidy=FALSE>>=
HELPrct <- mutate(HELPrct, subgrp = factor(substance, 
  levels=c("alcohol", "cocaine", "heroin"),
  labels=c("A", "C", "H")))
mod <- lm(cesd ~ subgrp, data=HELPrct)
HELPHSD <- TukeyHSD(mod, "subgrp")
HELPHSD
@
\Rindex{mplot()}%
<<help-hsd3,fig.height=3.5,fig.width=6>>=
mplot(HELPHSD)
@

De nuevo, podemos ver que el grupo de cocaína tiene significativamente menores puntajes de CESD que cualquiera de los otros grupos.

\chapter{Respuesta categórica, predicto cuantitativo}
\section{Respuesta categórica, predictor cuantitativo}
\myindex{logistic regression}%

La regresión logística está disponible en R usando la función \function{glm}, la cual permite una variedad de funciones de enlace y formas de distribuciones para modelos lineales generalizados, incluyendo la regresión logística.
\FoodForThought[-1cm]{La función \function{glm()} tiene el argumento \option{family}, el cual puede tomar la opción \option{link}(función de enlace). La función de enlace logit está predeterminada en link para la familia binomial, entonces no necesitamos especificarlo aquí. La forma más completa de uso sería \code{family=binomial(link=logit)}.}.}%
\Rindex{glm()}%
\Rindex{family option}%
\Rindex{exp()}%
\Rindex{msummary()}%
<<help-logit,tidy=FALSE>>=
logitmod <- glm(homeless ~ age + female, family=binomial, 
  data=HELPrct)
msummary(logitmod)
exp(coef(logitmod))
exp(confint(logitmod))
@

Podemos comparar dos modelos (para una prueba de múltiples grados de libertad). Por ejemplo, podríamos estar interesados en la asociación del estado de indigencia (homeless) y la edad para cada uno de los tres grupos de sustancia.
\Rindex{anova()}%
\Rindex{test option}%
<<tidy=FALSE>>=
mymodsubage <- glm((homeless=="homeless") ~ age + substance, 
  family=binomial, data=HELPrct)
mymodage <- glm((homeless=="homeless") ~ age, family=binomial, 
  data=HELPrct)
msummary(mymodsubage)
exp(coef(mymodsubage))
anova(mymodage, mymodsubage, test="Chisq")
@
Observamos que los grupos que consumen cocaína y heroína son significativamente menos probables a estar sin casa que aquellos sujetos envueltos en el alcohol, después de controlar la edad. (Un resultado similar se ve considerando solamente el status de si tiene vivienda y la sustancia).

<<>>=
tally(~ homeless | substance, format="percent", margins=TRUE, data=HELPrct)
@


\chapter{Resulados de análisis de supervivencia}
\myindex{survival analysis}%
\myindex{failure time analysis}%
\myindex{time to event analysis}%
Una extensiva cantidad de herramientas para análisis de sobrevivencia (tiempo a un evento) está disponible en el paquete \pkg{survival}

\section{Diagrama de Kaplan-Meier}

\myindex{Kaplan-Meier plot}%
\Rindex{survfit()}%
\Rindex{Surv()}%
\Rindex{conf.int option}%
\Rindex{xlab option}%
\begin{center}
<<help-km,fig.width=6,fig.height=3.9,tidy=FALSE,message=FALSE, fig=TRUE>>=
require(survival)
fit <- survfit(Surv(dayslink, linkstatus) ~ treat, 
  data=HELPrct)
plot(fit, conf.int=FALSE, lty=1:2, lwd=2, 
  xlab="tiempo (en días)", ylab="P(no ligados)")
legend(20, 0.4, legend=c("Control", "Tratamiento"), 
  lty=c(1,2), lwd=2)
title("Producto-Límite de los estimados de sobrevivencia(tiempo ligado)")
@
\end{center}

Vemos que los sujetos en el tratamiento (Health Evaluation and Linkage to Primary Care clinic) tuvieron significativamente más probabilidad de acoplarse al cuidado primario (menos probabilidad  a "sobrevivir") que el grupo control (cuidado normal)
\section{Modelo de riesgos proporcionales de Cox}
\myindex{Cox proportional hazards model}%
\myindex{proportional hazards model}%
\Rindex{coxph()}%

<<help-surv,tidy=FALSE>>=
require(survival)
summary(coxph(Surv(dayslink, linkstatus) ~ age + substance, 
  data=HELPrct))
@

Ni la edad ni el grupo de sustancia fueron significativamente asociados a estar en cuidado primario.

\chapter{Más de dos variables}
\section{Análisis de varianza (ANOVA) de dos (o más) vías}

Podemos ajustar un modelo ANOVA de dos o más vías, con o sin interacción, usando la misma sintaxis de modelaje.
\Rindex{median()}%
\Rindex{bwplot()}%
\Rindex{factor()}%
\Rindex{mutate()}%
\Rindex{aov()}%
<<help-aovplot>>=
HELPrct <- mutate(HELPrct, subgrp = factor(substance,
  levels=c("alcohol", "cocaine", "heroin"),
  labels=c("A", "C", "H")))
median(cesd ~ substance | sex, data=HELPrct)
bwplot(cesd ~ subgrp | sex, data=HELPrct)
@
<<help-aov2>>=
summary(aov(cesd ~ substance + sex, data=HELPrct))
@
<<help-aov3>>=
summary(aov(cesd ~ substance * sex, data=HELPrct))
@
Hay poca evidencia de interacción, aunque hay efectos principales significativos en los términos de la sustancia(\variable{substace}) y el sexo(\variable{sex}).

<<help-interaction,tidy=FALSE, fig=TRUE>>=
xyplot(cesd ~ substance, groups=sex, lwd=2,
  auto.key=list(columns=2, lines=TRUE, points=FALSE), 
  type='a', data=HELPrct)
@
\Rindex{auto.key option}%


\section{Regresión múltiple}
\myindex{multiple regression}%
\myindex{multivariate relationships}%

La regresión múltiple es una extensión lógica de comandos previamente señalados, donde algunos predictores adicionales son agregados. Esto permite a los estudiantes intentar desenvolver relaciones multivariadas. 

\InstructorNote[-2cm]{Tenemos la tendencia introducir la regresión lineal múltiple de forma temprana en nuestros cursos como una técnica puramente descriptiva, después regularmente volvemos a esta. La motivación para esto se encuentra descrita en  detalle en el volumen acompañante \emph{Start modelling with R}}

Aquí consideramos un modelo (de pendientes paralelas) para los síntomas depresivos como función del Puntaje del componente mental (MCS), edad (en años) y sexo del sujeto.

\myindex{msummary()}%
<<help-multreg>>=
lmnointeract <- lm(cesd ~ mcs + age + sex, data=HELPrct)
msummary(lmnointeract)
@
\myindex{anova()}%
\myindex{interactions}%
También podemos ajustar un modelo que incluye una interacción entre MCS y sexo.
<<help-multreg2>>=
lminteract <- lm(cesd ~ mcs + age + sex + mcs:sex, data=HELPrct)
msummary(lminteract)
anova(lminteract)
@
<<help-multreg3>>=
anova(lmnointeract, lminteract)
@

There is little evidence for an interaction effect, so we drop
this from the model.

\subsection{Visualizar los resultados de la regresión}

\label{sec:plotFun}
\Rindex{plotFun()}%
\Rindex{makeFun()}%
Las funciones \function{makeFun()} y \function{plotFun()} del paquete \pkg{mosaic} pueden ser utilizadas para desplegar los valores predichos de un modelo de regresión. Por ejemplo, podríamos desplegar los valores de CESD predichos para un rango de valores de MCS (puntuación del componente mental) en un sujeto hipotético, hombre de 36 años y en un sujeto hipotético mujer con la misma edad en el cual se utiliza un modelo pendientes paralelas (sin interacción).
<<makeFUN>>=
lmfunction <- makeFun(lmnointeract)
@

\Rindex{xyplot()}%
\Rindex{auto.key option}%
\Rindex{ylab option}%
\Rindex{groups option}%
\Rindex{add option}%
Ahora podemos graficar los valores predichos separadamente para sujetos masculinos y femeninos sobre valores del rango de MCS (puntaje del componente mental), junto con los datos observados de aquellos de 36 años..  
<<plotFUN,tidy=FALSE,fig.keep='last', fig=TRUE>>=
xyplot(cesd ~ mcs, groups=sex, auto.key=TRUE, 
  data=filter(HELPrct, age==36))
plotFun(lmfunction(mcs, age=36, sex="male") ~ mcs, 
  xlim=c(0, 60), lwd=2, ylab="predicted CESD", add=TRUE)
plotFun(lmfunction(mcs, age=36, sex="female") ~ mcs, 
  xlim=c(0, 60), lty=2, lwd=3, add=TRUE)
@


\subsection{Gráficos de coeficientes}

\myindex{coefficient plots}%
Es en ocasiones útil utilizar un gráfico de coeficientes para un modelo de regresión múltiple (junto con sus intervalos de confianza asociados)

\Rindex{mplot()}%
<<results=hide, fig=TRUE>>=
mplot(lmnointeract, rows=-1, which=7)
@

\FoodForThought[-4cm]{Los puntos más oscuros indican que los coeficientes de la regresión donde el intervalo de confianza al 95\% no incluye el valor de 0 de la hipótesis nula}

\Caution{Sea cuidadoso cuando ajusta la regresión con modelos con valores perdidos (ver también sección 13.11)}

\subsection{Diagnósticos de residuales}
\myindex{residual diagnostics}
\myindex{regression diagnostics}

Es sencillo realizar algunos diagnósticos de residuales para este modelo. Empezamos por agregar los valores ajustados y los residuales al conjunto de datos.
\FoodForThought[-1cm]{La función \function{mplot()} también puede ser utilizada para crear estos gráficos.}
\Rindex{resid()}%
\Rindex{fitted()}%
\Rindex{abs()}%
\InstructorNote{Aquí agregamos dos nuevas variables en un conjunto de datos existente. Es usualmente una buena práctica dar a los nuevos conjuntos de datos un nuevo nombre.}
<<tidy=FALSE>>=
HELPrct <- mutate(HELPrct, 
  residuals = resid(lmnointeract), 
  pred = fitted(lmnointeract))
@
<<tidy=FALSE, message=FALSE, fig=TRUE>>=
histogram(~ residuals, xlab="residuals", fit="normal", 
  data=HELPrct)
@

Podemos identificar que en el subconjunto de observaciones hay residuales extremadamente grandes.

\Rindex{abs()}%
<<>>=
filter(HELPrct, abs(residuals) > 25)
@

\Rindex{cex option}%
\Rindex{type option}%
<<tidy=FALSE, fig=TRUE>>=
xyplot(residuals ~ pred, ylab="residuals", cex=0.3,
  xlab="predicted values", main="predicted vs. residuals",
  type=c("p", "r", "smooth"), data=HELPrct)
@
<<tidy=FALSE, fig=TRUE>>=
xyplot(residuals ~ mcs, xlab="mental component score", 
  ylab="residuals", cex=0.3,
  type=c("p", "r", "smooth"), data=HELPrct)
@

El supuesto de normalidad, linealidad y homoscedasticidad parece razonable aquí.
\begin{problem}
El conjunto de datos \dataframe{RailTrail} dentro del paquete \pkg{mosaic}, incluye un conteo de cruces de un camino en Northampton, Massachusetts para 90 días en 2005. Las autoridades de la ciudad están interesadas en entender el uso de la red de caminos, y como cambia en función de la temperatura y el día de la semana. Describa la distribución de la variable \variable{avgtemp}
en terminos de su centro, dispersión y forma.
<<tidy=FALSE, fig=TRUE>>=
favstats(~ avgtemp, data=RailTrail)
densityplot(~ avgtemp, xlab="Average daily temp (degrees F)", 
  data=RailTrail)
@
\end{problem}
\begin{problem}
El conjunto de datos de \dataframe{RailTrail} también incluye una variable llamada \variable{cloudcover}. Describa la distribución de esta variable de la misma forma anterior.
\end{problem}
\begin{problem}
El conjunto de datos \dataframe{RailTrail} brinda datos sobre el conteo diario de cruces, llamado \variable{volume}. Describa la distribución de la variable de la misma forma anterior..
\end{problem}
\begin{solution}
<<>>=
favstats(~ volume, data=RailTrail)
densityplot(~ volume, xlab="# of crossings", data=RailTrail)
filter(RailTrail, volume > 700)
@
The distribution of daily crossings is approximately normally
distributed with mean 375 crossings  and standard deviation of 127 crossings.
There is one outlier with 736 crossings which occurred on a Monday holiday in the spring
(Memorial Day).  
\end{solution}
\begin{problem}
El conjunto de datos \dataframe{RailTrail} también contiene un indicador de si el día fue un día entre semana (\variable{weekday==1}), o un fin de semana/día libre (\variable{weekday==0}). Utilice \function{tally()} para describir la distribución de esta variable categorica. ¿Qué porcentaje de días son fines de semana/días libres?
\end{problem}
\begin{solution}
<<>>=
tally(~ weekday, data=RailTrail)
tally(~ weekday, format="percent", data=RailTrail)
@
Just over 30\% of the days are weekends or holidays.
\end{solution}
\begin{problem}
Use diagramas de caja que se encuentren uno al lado del otro para comparar la distribución de \variable{volume} por el tipo de día en el conjunto de datos \dataframe{RailTrail}. Pista: va necesitar transformar la variable numéricos en un factor variable usando as.factor() o usar la opción {\tt horizontal=FALSE}. ¿Qué concluye?
\end{problem}
\begin{problem}
Use gráficos de densidad traslapados para comprar la distribución de volume por tipo de día en el conjunto de datos RailTrail. 
¿Qué concluye?
\end{problem}
\begin{problem}
Cree un gráfico de dispersión de \variable{volume} en función de \variable{avgtemp} usando el conjunto de datos de \dataframe{RailTrail}, junto con la línea de regresión y un suavizador de gráfico de dispersión (curva de regresión local). ¿Qué observa en esta relación? 
\end{problem}
\begin{problem}
Usando el conjunto de datos de \dataframe{RailTrail}, ajuste un modelo de regresión multiple para \variable{volume} como función de \variable{cloudcover}, \variable{avgtemp}, \variable{weekdays} y la interacción entre el tipo de día y la temperatura promedio. ¿Hay evidencia para mantener la interacción con un nivel de significancia de $\alpha=0.05$ \variable{avgtemp}, 
\variable{weekday} and the interaction
\end{problem}
\begin{problem}
Use la función \function{makeFun()} para calcular el número predicho de cruces en un día de la semana con una temperatura promedio de 60 grados y sin nubes. Verifique este cálculo usando los coefficientes del modelo.
<<include=FALSE>>=
fm <- lm(volume~cloudcover+avgtemp+weekday+weekday:avgtemp, data=RailTrail)
@
<<>>=
coef(fm)
@
\end{problem}

\begin{problem}
 Use \function{makeFun()} y \function{plotFun()} para desplegar los valores predichos para el número de cruces en días de la semana y en fines de semana/días libres para temperatures promedio entre 30 y 80 grados en días nubosos (\variable{cloudcover=10}) 
\end{problem}
\begin{problem}
Usando un modelo de regresión múltiple, genere un histograma (con una curva de densidad normal sobre él) para evaluar la normalidad de los residuales.
\end{problem}
\begin{problem}
Usando un modelo de regresión múltiple, genere un histograma (con una curva de densidad normal sobre él) para evaluar la normalidad de los residuales.
\end{problem}
\begin{problem}
Usando el mismo modelo, genere un gráfico de dispersión de los residuales contra los valores predichos y comente la linealidad del modelo y el supuesto de igualdad de varianza.
\end{problem}


\chapter{Distribuciones de probabilidad \&\ variables aleatorias}
\label{sec:DiscreteDistributions}
\label{sec:probability}
\myindex{random variables}%

\R\ puede calcular números relacionados a distribuciones de todo tipo. Está también dirigido a generar muestras aleatorias de estas distribuciones, que pueden ser utilizadas para simulación y exploración.
<<probdist, fig=TRUE>>=
xpnorm(1.96, mean=0, sd=1)    # P(Z < 1.96)
@
\Rindex{qnorm()}%
\Rindex{dnorm()}%
\Rindex{pnorm()}%
\Rindex{xpnorm()}%
\Rindex{rnorm()}%
\Rindex{integrate()}%
<<>>=
# valor que satisface P(Z < z) = 0.975
qnorm(.975, mean=0, sd=1)   
integrate(dnorm, -Inf, 0)   # P(Z < 0)
@

Una exposición similar es disponible para la distribución F

<<fig=TRUE>>=
xpf(3, df1=4, df2=20)
@
La siguiente tabla muestra los nombres de base para las distribuciones de probabilidad disponibles en la base de \R\. Estas funciones pueden tener el prefijo por {\tt d}  para encontrar la función de densidad de la distribución, {\tt p} para encontrar la distribución acumulada, {\tt q} para encontrar cuantilos y {\tt r} para generar resultados aleatorios. Por ejemplo, para encontrar la función de densidad de una variable aleatoria, use el comando \function{dexp()}. La función \function{qDIST()} es el inverso de la función \function{pDIST()}, para un nombre base dado el nombre de tipo DIST. 
\begin{center}
\begin{tabular}{|c|c|c|} \hline
Distribución    & Nombre de base                 \\ \hline
Beta            &  {\tt beta}        \\
binomial        &  {\tt binom}    \\
Cauchy          &  {\tt cauchy}   \\
chi-square      &  {\tt chisq}    \\
exponential     &  {\tt exp}      \\
F               &  {\tt f}        \\
gamma           &  {\tt gamma}    \\
geometrica      &  {\tt geom}     \\
hypergeometrica &  {\tt hyper}    \\
logistica       &  {\tt logis}    \\
lognormal       &  {\tt lnorm}    \\
binomial negativa &  {\tt nbinom} \\
normal         &  {\tt norm}      \\
Poisson        &  {\tt pois}      \\
T de Student   &  {\tt t}        \\
Uniforme       &  {\tt unif}     \\
Weibull        &  {\tt weibull}   \\ \hline
\end{tabular}
\end{center}
\DiggingDeeper{El \function{fitdistr()} dentro del paquete \pkg{MASS} facilita la estimación de los parámetros para muchas distribuciones}
La funcion \function{plotDist()} puede ser utilizada para desplegar gráficos de varias maneras.
\Rindex{plotDist()}%
<<tidy=FALSE, fig=TRUE>>=
plotDist('norm', mean=100, sd=10, kind='cdf')
@
<<tidy=FALSE, fig=TRUE>>=
plotDist('exp', kind='histogram', xlab="x")
@
Note que esto ajusta el parametro del rango a 1 y la isguiente función hace lo mismo:
<<eval=FALSE, tidy=FALSE, fig=TRUE>>=
plotDist('exp', rate=1, kind='histogram', xlab="x")
@

<<tidy=FALSE,fig.keep='last', fig=TRUE>>=
plotDist('binom', size=25, prob=0.25, xlim=c(-1,26))
@

Distribuciones múltiples pueden ser incluidas en el mismo gráfico.
\Rindex{groups option}%
\Rindex{type option}%
\Rindex{under option}%
\Rindex{lwd option}%
\Rindex{pch option}%
<<tidy=FALSE,fig.keep='last', fig=TRUE>>=
plotDist("binom", size=100, prob=.3, col="black", lwd=3, pch=16)
plotDist("norm", mean=30, sd=sqrt(100 * .3 * .7), 
  groups = abs(x - 30) > 6 , type="h", under=TRUE)
@

La función \function{plotFun()} puede ser utilizada para graficar una función arbitraria (en este caso una variable aleatoria exponencial).

\Rindex{makeFun()}%
\Rindex{rexp()}%
\Rindex{plotFun()}%
\Rindex{histogram()}%
\Rindex{width option}%
\Rindex{center option}%
\Rindex{add option}%
<<fig.keep="last", fig=TRUE>>=
f <- makeFun(2*exp(-2*x) ~ x)   # exponential with rate parameter 2
x <- rexp(1000, rate=2)
histogram(~ x, width=0.2, center=0.1)
plotFun(f(x) ~ x, col="red", lwd=2, add=TRUE)
@
\begin{problem}
Genere una muestra de 1000 variables aleatorias exponenciales con el parámetro igual a 2, calcule la media de estas variables.
\end{problem}
\begin{solution}
<<expprob>>=
x <- rexp(1000, rate=2)
mean(x)
@
\end{solution}

\begin{problem}
Encuentre la mediana de la variable aleatoria X, si esta se distribuye exponencialmente con un parámetro igual a 10.
\end{problem}
\begin{solution}
<<expprob2>>=
qexp(.5, rate=10)
@
\end{solution}

\chapter{Cálculos de Potencia}
\vspace*{-.7cm}
Aunque no es generalmente un tema de trato fundamental en los cursos introductorios, los cálculos de potencia y tamaño de muestra ayudan a reforzar ideas clave de estadística. En esta sección, podremos explorar cómo R puede ser utilizado para llevar a cabo cálculos de potencia, usando un abordaje analítico. Consideramos un problema simple con dos pruebas de hipótesis (la prueba t y la prueba de signos) con comparaciones de una cola.

Vamos a comparar la potencia de la prueba de signos y la potencia de la prueba basada en la teoría normal (prueba t de una cola con una muestra) asumiendo que $\sigma$ es conocido. 
Sea $X_1, ..., X_{25}$ una variables aleatorias independientes distribuidas $N(0.3, 1)$ (esto es un alterno para el que deseamos calcular la potencia). Considere probar la hipotesis nula $H_0: \mu=0$ contra $H_A: \mu>0$, con una nivel de significancia de $\alpha=.05$. 


\section{Prueba de signos}

Empezamos por calcular el error Tipo I para la prueba de signos. Aquí, queremos rechazar que el número de valores positivos es grande. Bajo la hipótesis nula, esto se distribuye como una variable aleatoria binomial, con n=25 intentos y p=0.5 probabilidad de valores positivos. Consideremos valores entre 15 y 19.

<<pbinom>>=
xvals <- 15:19
probs <- 1 - pbinom(xvals, size=25, prob=0.5)
cbind(xvals, probs)
qbinom(.95, size=25, prob=0.5)
@
Entonces, vemos que si decidimos rechazar la hipotesis cuando el número de valores positivos es de 17 o mayor, vamos a tener un nivel de $\alpha$ de \code{round(1-pbinom(16, 25, 0.5), 3)}, lo cual está cerca del valor nominal en el problema.

Calculamos la potencia de la prueba de signos como se muestra. La probabilidad de que $X_i > 0$, dado que $H_A$ es cierta es dada por:
<<pnorm1>>=
1 - pnorm(0, mean=0.3, sd=1)
@
Esto lo podemos ver gráficamente usando el comando:
\begin{center}
<<pnorm2,fig.width=5,fig.height=1.9>>= 
xpnorm(0, mean=0.3, sd=1, lower.tail=FALSE)
@
\end{center}
La potencia basada en que la hipótesis alternativa es igual a la probabilidad de conseguir 17 o más valores positivos, dado que $p=0.6179$, es la siguiente

\Rindex{pbinom()}%
<<pbinom2>>=
1 - pbinom(16, size=25, prob=0.6179)
@
La potencia es modesta.

\section{Prueba t}

Después, calculamos la potencia de la prueba basada en la teoría normal. Para seguir la comparación justa, vamos a poner nuestro $\alpha$ en un nivel igual a 0.05388

<<tidy=FALSE>>=
alpha <- 1-pbinom(16, size=25, prob=0.5); alpha
@

Primero encontramos la región de rechazo. 
<<tidy=FALSE>>=
n <- 25; sigma <- 1 # given
stderr <- sigma/sqrt(n)
zstar <- qnorm(1-alpha, mean=0, sd=1)
zstar
crit <- zstar*stderr
crit
@


Entonces, rechazamos por las medias observadas, mayores a \Sexpr{round(crit,3)}.  

Para calcular la potencia de esta prueba de una cola, debemos encontrar la probabilidad de la hipótesis alternativa a su punto límite de la derecha

<<>>=
power <- 1 - pnorm(crit, mean=0.3, sd=stderr)
power
@

La potencia de la prueba basada en la teoría normal es de \Sexpr{round(crit, 3)}. Para dar una revisión (o para futuros cálculos de este tipo) podemos usar la función \function{power.t.test()}
<<>>=
power.t.test(n=25, delta=.3, sd=1, sig.level=alpha, alternative="one.sided",
type="one.sample")$power
@

Esta forma analítica (de aproximación basada en la fórmula) permite un estimado similar al valor que calculamos directamente.

Sobre todo, vemos que la prueba t tiene una mayor potencia que la prueba de signos, en especial si los datos son verdaderamente normales.  \FoodForThought{Calcular la potencia empíricamente demuestra el poder que tienen las simulaciones}
\begin{problem}
\label{prob:power1}%
Encuentre la potencia de una prueba t de dos colas con dos muestras donde ambas distribuciones son aproximadamente distribuidas normalmente con la misma desviación estándar, pero el grupo difiere en un 50\% de la desviación estándar. Asuma que hay \Sexpr{n} observaciones por grupo y un nivel de significancia de \Sexpr{alpha}

\end{problem}
\begin{solution}
<<setup1,echo=FALSE>>=
n <- 100
alpha <- 0.01
@
<<power>>=
n
alpha
power.t.test(n=n, delta=.5, sd=1, sig.level=alpha)
@
\end{solution}
\begin{problem}
Encuentre el tamaño de muestra necesario para tener un 90\% de potencia para una prueba t de dos grupos donde la diferencia entre las medias es el 25\% de la desviación estándar en los grupos (con un $\alpha$ de 0.05).
\end{problem}
\begin{solution}
<<power2>>=
power.t.test(delta=.25, sd=1, sig.level=alpha, power=0.90)
@
\end{solution}

\chapter{Manejo de datos}

\label{sec:manipulatingData}%
\myindex{data management}%
\myindex{thinking with data}%

\FoodForThought{El libro  \emph{Empiece a enseñar con R} caracteriza una extensiva sección en manejo de datos, incluyendo el uso de la función read.file() para carga datos en R y RStudio}

\vspace*{-1cm}
El manejo de datos es una capacidad clave para permitir a los estudiantes (e instructores) a "computar con los datos" o como Diane Lambert de Google ha manifestado, "pensar con los datos". Tendemos a mantener el manejo de datos de los estudiantes en un mínimo durante la parte temprana de los cursos introductorios de estadística, después gradualmente introducimos temas como sean necesarios. Para cursos donde los estudiantes llevan a cabo proyectos sustantivos, el manejo de datos es más importante. Este capítulo describe algunas tareas clave en el manejo de datos.
\myindex{read.file()}%

\FoodForThought{nombre para un conjunto de datos en R).
Los paquetes \pkg{dplyr} y \pkg{tidyr} brindan una elegante herramienta para el manejo de datos y facilitan la habilidad de los estudiantes a computar con los datos. Hadley Wickham, autor de los paquetes, sugiere que hay seis expresiones (o verbos) implementados dentro de estos paquetes que permiten una larga lista de tareas sean realizadas. Filtrar (mantener filas con criterios de emparejamiento), seleccionar (elegir columnas por nombre), ordenar (reordenar filas), mutar (agregar nuevas variables), resumir (reducir las variables a valores) y agrupar por (colapsar grupos). Vea url{http://www.amherst.edu/~nhorton/precursors}  para más detalles y recursos.
}

\section{Inspección de dataframes}
\myindex{inspecting dataframes}%
\myindex{dataframes!inspecting}%
La función \function{inspect()} puede ser útil describiendo las variables del dataframe (el nombre para un conjunto de datos en R).
\Rindex{inspect()}%
<<>>=
inspect(iris)
@
El dataframe \dataframe{iris} incluye una variable categórica y cuatro variables cuantitativas


\section{Agregar nuevas variables a un dataframe}
\myindex{dataframe}%
Podemos agregar variables adicionales a un dataframe existente usando \function{mutate()}. Pero primero debemos crear una versión más pequeña del conjunto de datos \dataframe{iris}.

\Rindex{select()}%
\myindex{iris dataset}%
<<mr-adding-variable2>>=
irisSmall <- select(iris, Species, Sepal.Length)
@

\myindex{adding variables}%
\Rindex{mutate()}%
\Rindex{cut()}%
<<mr-adding-variable,tidy=FALSE>>=
# cortar pedazos de los datos en cajas
irisSmall <- mutate(irisSmall, 
  Length = cut(Sepal.Length, breaks=4:8))    
@

\myindex{pipe operator}%
\Rindex{\%>\%}%
Comandos múltiples pueden ser encadenados usando el operador {\tt \%>\%} (pipa):
<<>>=
irisSmall <- iris %>%
  select(Species, Sepal.Length) %>%
  mutate(Length = cut(Sepal.Length, breaks=4:8))
@
Note que en este uso el primer argumento de \function{select} es la primera variable (como lo hereda de los datos de la pipa anterior).


\FoodForThought[1cm]{La función \function{cut()} tiene la opción de etiqueta que puede ser utilizada para especificar más nombres para describir los grupos}
<<"mr-adding-variable2-again">>=
head(irisSmall)
@
\Rindex{head()}%
\myindex{display first few rows}%

\myindex{CPS85 dataset}%
El conjunto de datos \dataframe{CPS85} contiene datos de una Encuesta Actual de Población (Actual en 1985, eso es). Dos de las variables en este conjunto de datos son edad y educ. Podemos estimar el número de años que el trabajador ha estado en la fuerza de trabajo desde que completó la educación, asumiendo que ha estado en la fuerza de trabajo desde que completó su educación y que su edad en la graduación es 6 años más que el número de años de educación obtenida. Podemos agregar esto como una nueva variable en el conjunto de datos usando \function{mutate()}
\myindex{CPS85 dataset}%
\Rindex{mutate()}%
<<>>=
CPS85 <- mutate(CPS85, workforce.years = age - 6 - educ)
favstats(~ workforce.years, data=CPS85)
@
De hecho, esto es lo que se hizo para todos excepto uno de los casos para crear la variable \variable{exper} que está ya en los datos de \dataframe{CPS85}.
<<>>=
tally(~ (exper - workforce.years), data=CPS85)
@

\section{Desechando variables}
\myindex{dropping variables}%
\Rindex{filter()}%
\Rindex{select option}%
Puesto que ya tenemos la variable \variable{exper}, no hay una verdadera razón para dejarnos nuestra nueva variable. 
Desechémosla. Note una utilización inteligente del signo de menos

<<>>=
names(CPS85)
CPS1 <- select(CPS85, select = -matches("workforce.years"))
names(CPS1)
@

Cualquier número de variables puede ser descartado o mantenido de una manera similar.
<<>>=
CPS1 <- select(CPS85, select = -matches("workforce.years|exper"))
@


\section{Renombrando variables}
\myindex{renaming variables}%
\Rindex{rename()}%
\Rindex{row.names()}%
La columna de nombres (variables) de un conjunto de datos puede ser cambiada usando la función \function{rename()} en el paquete \pkg{dplyr}.
<<>>=
names(CPS85)
CPSnew = rename(CPS85, workforce=workforce.years)
names(CPSnew)
@

Los nombres de las filas pueden ser cambiados con una indicación simple, usando \function{row.names()}.

\Rindex{names()}%
\myindex{faithful dataset}%
El conjunto de datos \dataframe{faithful} (en el paquete \pkg{datasets}, que está siempre disponible) tiene nombres muy poco desafortunados.
\FoodForThought{Es una buena idea establecer prácticas de elección de nombres de variables desde el primer día.}
<<>>=
names(faithful)
@

Las medidas son la duración de una erupción y el tiempo hasta la erupción subsecuente, entonces, demos a estar unos mejores nombres.
<<tidy=FALSE>>=
faithful <- rename(faithful, 
  duration = eruptions, 
  time.til.next=waiting)
names(faithful)
@
\myindex{faithful dataset}%
\begin{center}
<<"mr-faithful-xy">>=
xyplot(time.til.next ~ duration, alpha=0.5, data=faithful)
@
\end{center}
Si la variable que contiene el conjunto de datos es modificada o utilizada para almacenar un objeto diferente, los datos originales del paquete pueden ser recuperados usando \function{data()}.
\Rindex{data()}%
<<>>=
data(faithful)
head(faithful, 3)
@

\begin{problem}
Usando el conjunto de datos \dataframe{faithful}, haga un gráfico de dispersión de la duración de la erupción contra el tiempo desde la erupción pasada.
\end{problem}


\section{Creando subconjuntos de datos}
\myindex{creating subsets}%
\myindex{subsetting dataframes}%
\myindex{dataframes!subsetting}%
\label{sec:subsets}
Podemos también usar \function{filter()} para reducir el tamaño del conjunto de datos seleccionando sólo algunas filas.
\begin{center}
<<"mr-faithful-long-xy">>=
data(faithful)
names(faithful) <- c('duration', 'time.til.next')
# any logical can be used to create subsets
faithfulLong <- filter(faithful, duration > 3)        
xyplot( time.til.next ~ duration, data=faithfulLong )
@
\end{center}


\section{Ordenar dataframes}
\myindex{sorting dataframes}%
\myindex{dataframes!sorting}%
\Rindex{arrange()}%

Los conjuntos de datos pueden ser ordenados usando la función \function{arrange()}.
<<>>=
head(faithful, 3)
sorted <- arrange(faithful, duration)
head(sorted, 3)
@
\Caution{usualmente es mejor hacer conjuntos de datos nuevos en lugar de modificar el original}




\section{Uniendo conjuntos de datos}
\myindex{merging dataframes}%
\myindex{dataframes!merging}%

<<echo=FALSE>>=
OLD <- options(width=90)
@
El conjunto de datos \dataframe{fusion1} en el paquete \pkg{fastR} contiene información del genotipo para la SNP (Polimorfismo de nucleotido simple) en el gen \variable{TCF7L2}. El conjunto de datos pheno contiene fenotipos (incluyendo diabetes tipo 2 en estado caso/control) para un grupo de individuos con intersecciones. Podemos unir estos y explorar la asociación entre genotipos y fenotipos usando \verb!merge()!.

\Rindex{arrange()}%
<<warning=FALSE,message=FALSE>>=
require(fastR)
require(dplyr)
fusion1 <- arrange(fusion1, id)
head(fusion1, 3)
head(pheno, 3)
@

\Rindex{arrange()}%
\Rindex{all.x option}%
\Rindex{by.x option}%
<<message=FALSE, warning=FALSE,tidy=FALSE>>=
require(tidyr)
fusion1m <- inner_join(fusion1, pheno, by='id')
head(fusion1m, 3)
@
\Rindex{tidyr package}%

\myindex{fusion1 dataset}%
Ahora estamos listos para iniciar nuestro análisis
<<"mr-fusion1-xtabs">>=
tally(~t2d + genotype, data=fusion1m)
@

\begin{problem}
En el conjunto de datos \dataframe{fusion2} en el paquete fastR contiene genotipos para otro SNP. Una \dataframe{fusion1}, \dataframe{fusion2} y \dataframe{pheno} en un solo conjunto de datos. 

Note que fusion1, fusion2 tienen las mismas columnas.
<<>>=
names(fusion1)
names(fusion2)
@
Usted tal vez quiere usar argumentos \option{suffixes} a \function{merge()} o renombrar las variables después de que las haya terminado de unirlos para hacer el conjunto de datos resultante más fácil de navegar. 
Ordene su conjunto de datos eliminando columnas que son redundantes o que no desea tener en su conjunto de datos final.
\end{problem}

\section{Tajando y cortando}
\myindex{reshaping dataframes}%
\myindex{dataframes!reshaping}%
\myindex{transforming dataframes}%
\myindex{transposing dataframes}%
The \pkg{tidyr} package provides a flexible way to change the arrangement of data.  
El paquete \pkg{tidyr} provee una forma flexible para cambiar el ordenamiento de los datos. Fue diseñado para convertir entre largas y amplias versiones de series de datos de series de tiempo y sus argumentos son nombrados con eso en mente.
\FoodForThought{Las viñetas que acompañan a los paquetes \pkg{tidyr} y \pkg{dplyr} se caracterizan por tener una cantidad de ejemplos útiles de manipulación de datos común}

Una situación común es cuando queremos convertir de una forma amplia a una forma larga por cambios en la perspectiva de lo que la unidad de observación es. Por ejemplo en los datos \dataframe{traffic}, cada fila es un año y los se da en cada una los datos para diferentes estados.

<<"mr-traffic-reshape">>=
traffic
@
Podemos darle un nuevo formato a esto de tal forma que cada fila contenga una medida para un solo estado en un solo año

\Rindex{gather()}%
<<tidy=FALSE>>=
longTraffic <- traffic %>% 
  gather(state, deathRate, ny:ri) 
head(longTraffic)
@

También podemos darle formato de otra forma, en esta ocasión, teniendo todos los datos para un estado en una fila del conjunto de datos.
<<tidy=FALSE>>=
stateTraffic <- longTraffic %>% 
  select(year, deathRate, state) %>%
  mutate(year=paste("deathRate.", year, sep="")) %>%
  spread(year, deathRate)
stateTraffic
@
\Rindex{spread()}%
\Rindex{select()}%
\Rindex{mutate()}%
\Rindex{paste()}%

\section{Creación de variables derivadas}
\myindex{derived variables}

Existen varias funciones que ayuda a facilitar la creación o recodificación de variables

\subsection{Creando variables categóricas de una variable cuantitativa}

De forma siguiente vamos a mostrar como crear una variable categórica de 3 niveles con cortes en 20 y 40 para la escala del CESD (que tiene un rango de 0 a 60)

\Rindex{cut()}%
\Rindex{mutate()}%
\Rindex{include.lowest option}%
\Rindex{breaks option}%
<<tidy=FALSE>>=
favstats(~ cesd, data=HELPrct)
HELPrct <- mutate(HELPrct, cesdcut = cut(cesd, 
  breaks=c(0, 20, 40, 60), include.lowest=TRUE))
bwplot(cesd ~ cesdcut, data=HELPrct)
@
\Rindex{ntiles()}%
\FoodForThought{La función \function{ntiles} puede automatizar la creación de grupos en este aspecto}

Puede ser preferible darle mejor nombre a las etiquetas.
<<tidy=FALSE>>=
HELPrct <- mutate(HELPrct, cesdcut = cut(cesd, 
  labels=c("low", "medium", "high"),
  breaks=c(0, 20, 40, 60), include.lowest=TRUE))
bwplot(cesd ~ cesdcut, pch="|", data=HELPrct)
@

La función \function{derivedFactor} es incluso más general y puede ser utilizada para este propósito.

\Rindex{derivedFactor()}%
<<>>=
HELPrct <- mutate(HELPrct, 
  anothercut = derivedFactor(
    low = cesd >= 0 & cesd <= 20,
    medium = cesd > 20 & cesd <= 40,
    high = cesd > 40))
@


\subsection{Reordenando factores}
\myindex{reordering factors}%
\myindex{factor reordering}%
\Rindex{relevel()}%
\Rindex{mutate()}%
\Rindex{coef()}%
\Rindex{tally()}%
Como predeterminado R utiliza el primer nivel en el orden lexicográfico como grupo de referencia para el modelaje. Esto puede ser anulado usando la función relevel (ver también reorder()).
<<tidy=FALSE>>=
tally(~ substance, data=HELPrct)
coef(lm(cesd ~ substance, data=HELPrct))
HELPrct <- mutate(HELPrct, subnew = relevel(substance, 
  ref="heroin"))
coef(lm(cesd ~ subnew, data=HELPrct))
@

\section{Estadísticas agrupadas}
\label{sec:groupby}

\myindex{group-wise statistics}%
\Rindex{select()}%

A veces puede ser útil calcular estadísticas de resumen por grupo, y agregar estas en un conjunto de datos. La función group_by() en el paquete dplyr facilita este proceso. Aquí demostramos cómo agregar una variable que contiene la media de la edad de los sujetos por grupo de sustancia.

\Rindex{favstats()}%
\Rindex{group\_by()}%
\Rindex{left\_join()}%
\Rindex{summarise()}%
\Rindex{nrow()}%
<<tidy=FALSE>>=
favstats(age ~ substance, data=HELPrct)
ageGroup <- HELPrct %>% 
  group_by(substance) %>%
  summarise(agebygroup = mean(age))
ageGroup
nrow(ageGroup)
nrow(HELPrct)
HELPmerged <- left_join(ageGroup, HELPrct, by="substance") 
favstats(agebygroup ~ substance, data=HELPmerged)
nrow(HELPmerged)
@


\section{Contabilizando datos perdidos}
\label{sec:miss}

\myindex{missing data}%
\myindex{incomplete data}%
\Rindex{select()}%
\Rindex{dim()}%
\Rindex{NA character}%
Los valores perdidos salen a flote en casi todas las investigaciones en el mundo real. \R utiliza el símbolo \variable{NA} como un indicador de datos faltantes. El conjunto de datos \dataframe{HELPmiss} dentro del paquete \pkg{mosaicData} incluye todos los n=470 sujetos ligados a la investigación de base (incluyendo el n=17 de sujetos con algunos datos faltantes que no fueron incluidos en \dataframe{HELPrct}).  
\myindex{HELPmiss dataset}%
<<tidy=FALSE>>=
smaller <- select(HELPmiss, cesd, drugrisk, indtot, mcs, pcs, 
  substance)
dim(smaller)
summary(smaller)
@

De los 470 sujetos en las 6 variables del conjunto de datos, solamente \variable{drugsrisk}, \variable{indtot}, \variable{mcs} y \variable{pcs} tienen valores faltantes

\Rindex{with()}%
\Rindex{na.omit()}%
\Rindex{favstats()}%
\Rindex{is.na()}%
\Rindex{sum()}%
\Rindex{nrow()}%
\Rindex{ncol()}%
<<tidy=FALSE>>=
favstats(~ mcs, data=smaller)
with(smaller, sum(is.na(mcs)))
nomiss <- na.omit(smaller)
dim(nomiss)
nrow(nomiss)
ncol(nomiss)
favstats(~ mcs, data=nomiss)
@

Alternativamente, podemos generar el mismo conjunto de datos usando condiciones lógicas.
<<tidy=FALSE>>=
nomiss <- filter(smaller, 
  (!is.na(mcs) & !is.na(indtot) & !is.na(drugrisk)))
dim(nomiss)
@

<<echo=FALSE>>=
options(OLD) 
@

\chapter{Health Evaluation (HELP) Study}

\label{sec:help}

\myindex{HELP study}%
\myindex{Health Evaluation and Linkage to Primary Care study}%
Muchos de los ejemplos en esta guía utilizaron datos del estudio HELP, una prueba clínica aleatorizada para pacientes en edad adulta, hospitalizados, reclutados de una unidad de desintoxicación. Los pacientes sin médico de cuidados primarios fueron aleatorizados para recibir evaluación multidisciplinaria y una pequeña intervención motivacional o cuidado usual, con la meta de unirlos al cuidado médico primario. Los fondos para el estudio HELP fueron previstos por el Instituto Nacional sobre Abuso de Alcohol y Alcoholismo (R01-AA10870, Samet PI) y el Instituto Nacional sobre Abuso de Droga (R01-DA10019, Samet PI). Los detalles de la prueba aleatorizada así como los resultados de análisis adicionales han sido publicados\cite{same:lars:hort:2003,lieb:save:2002,kert:hort:frie:2003}.

Los sujetos elegibles eran adultos, que hablaran inglés o español, que reportaran el alcohol, la heroína o la cocaína como su droga de preferencia, que residieran en la proximidad de la clínica de cuidado primario a la cual sería referido, o si fuera el caso que no tuviera casa. Pacientes que tuvieran relaciones establecidas con el cuidado primario que planeaban continuar en estos programas, demencia significativa, planes específicos de dejar el área de Boston lo cual obstruiría la participación en la investigación, fallo en proveer información de contacto para rastreo o embarazo fueron excluidos.

Los sujetos fueron entrevistados en una línea de base durante su estadía en el programa de desintoxicación y se realizaron entrevistas de seguimiento cada 6 meses por 2 años. Variables continuas, conteos, variables discretas, predictores de tiempo de sobrevivencia y otros resultados fueron recolectados en cada una de estas cinco ocasiones. La Comisión Revisora Institucional del Centro Médico de la Universidad de Boston aprobó todos los aspectos del estudio, incluyendo la creación de conjuntos de datos sin identificación. Medidas de protección adicional fue asegurada por emisión de un Certificado de Confidencialidad del Departamento de Salud y Servicios Humanos.


El paquete \pkg{mosaicData} contiene algunas formas del conjunto de datos \dataframe{HELP} sin identificación. Nos vamos a concentrar en HELPrct que contiene 27 variables de 453 sujetos con un mínimo de datos faltantes. Las variables incluidas en el conjunto de datos de HELP son descritas en la Tabla 14.1. Más información puede ser encontrada en: http://www.amherst.edu/~nhorton/r2. Una copia de los instrumentos de estudio puede ser encontrada en: http://www.amherts.edu/~nhorton/help 
\begin{longtable}{|p{2.1cm}|p{6.8cm}|p{3.5cm}|}
\caption{Descripción de las variables en el Conjunto de datos \dataframe{HELprct}}
\label{tab:helpvars} \\
\hline
Variable & Descripción(valores) &	Nota \\ \hline
\variable{age} & Edad de referencia(en años) (rango 19--60) & \\ \hline
\variable{anysub} & Uso de cualquier sustancia post desintoxicación & vea también \variable{daysanysub}
\\ \hline
\variable{cesd} & Escala del Centro de Estudios Epidemiológicos en Depresión (rango de 0--60, puntajes mayores indican mayores síntomas depresivos) & \\ \hline
\variable{d1} & Cuántas veces ha sido hospitalizado por problemas médicos(en toda la vida) (rango 0-100)  & \\ \hline
\variable{daysanysub} & Tiempo (en días) después del primer uso de cualquier sustancia post-desintoxicación (rango 0--268) & vea también \variable{anysubstatus} \\ \hline
\variable{dayslink} & Tiempo (en días) de asociación al cuidado primario(rango 0--456)  & vea también \variable{linkstatus}
\\ \hline
\variable{drugrisk} & Puntaje sobre riesgo a drogas del Risk-Assessment Baterry (RAB) (rango 0--21)  & vea también \variable{sexrisk}
\\ \hline
\variable{e2b} & Número de veces en los últimos 6 meses que ha entrado a un programa de desintoxicación (rango 1--21)  & \\ \hline
\variable{female} & Género del entrevistado (0=hombre, 1=mujer)  &
\\ \hline
\variable{g1b} & Experimentó pensamientos serios de suicidio (últimos 30 días, valores 0=no, 1=sí)  &
\\ \hline
\variable{homeless} & Ha dormido 1 o más noches en la calle o un albergue en los últimos 6 meses(0=no, 1=sí) & 
\\ \hline
\variable{i1} & Número promedio de bebidas (en unidades estándar, consumidas por día(en los últimos 30 días, rango 0-184) & vea también \variable{i2}
\\ \hline
\variable{i2} & Máximo número de bebidas (en unidades estándar) consumidas por día (en los últimos 30 días, rango 0--184) & vea también \variable{i1}
\\ \hline
\variable{id} & Identificador del sujeto (1--470) &
\\ \hline
\variable{indtot} & Puntaje total en el Inventorio de Consecuencias del uso de drogas (rango 4--45)  &
\\ \hline
\variable{linkstatus} & Asociación post-desintoxicación al cuidado primario (0=no, 1=sí)  & vea también \variable{dayslink}
\\ \hline
\variable{mcs} & Puntaje del Componente Mental SF-36 (rango 14-75, puntajes altos son preferibles)  & vea también \variable{pcs}
\\ \hline
\variable{pcs} & Puntaje del Componente Físico SF-36(rango 14-75, puntajes altos son preferibles)  & see also \variable{mcs}
\\ \hline
\variable{pss\_fr} & Apoyo social percibido (amigos, rango 0-14) & 
\\ \hline
\variable{racegrp} & Raza/etnia (negro, blanco, hispano u otro)  &  \\ \hline
\variable{satreat} &Cualquier tratamiento de abuso de sustancias de BSAS al inicio (0=no, 1=sí)  &  \\ \hline
\variable{sex} & Sexo del entrevistado (hombre o mujer)  & \\ \hline
\variable{sexrisk} & Risk-Assessment Battery (RAB) sex risk score  (range 0--21)  & ver también \variable{drugrisk}
\\ \hline
\variable{substance} & Principal sustancia de abuso (alcohol, cocaína, heroína) &
\\ \hline
\variable{treat} & Aleatorización del grupo(Aleatorizado a una clínica HELP, no o sí) & 
\\ \hline
\end{longtable}
\noindent
Notas: El rango se provee para las variables continuas.



\chapter{Ejercicios y problemas}

La primera parte del número del ejercicio dice de qué capítulo viene.

\shipoutProblems


%\backmatter

\bibliographystyle{alpha}
\bibliography{../include/USCOTS}

\printindex

\end{document}
